# 진짜 최종 구현 코드

1. 문제의 본질
원래 amount는 
- offer completed 시점에 붙어있던 값임
- 근데 이 값이 항상 위 조건을 따르진 않았음

2. 1차 해결 로직 : completion_amount_current
offer received를 시작 시간으로 보고 offer completed가 되는 시간까지 사이의 amount를 더한 값

3. 2차 해결 로직 : completion_amount_prev_received
1차 해결 로직으로 구할 수 없는 경우(76건)
- 같은 프로모션(offer)가 한 번 더 온 경우
- received(1) -> amount -> received(2) -> viewed -> completed = amount의 경우
    1차 로직으로는 received(2)부터 completed 까지의 amount를 더함.
    이렇게 되면 만약 received(1)에 대한 completed일 경우 received(1)와 received(2) 사이 발생한 amount를 제외시키게됨 -> difficulty 미충족
- 이를 해결하기 위해 received(2) 이전의 received(1)을 기준으로 계산하는 로직 만듬

4. 최종 df는?
2가지 로직에 충족한 amount를 맞게 적용
- 기본은 completion_amount_current으로
- 부족한 경우 completion_amount_prev_received를 적용

In [36]:
import numpy as np
import pandas as pd

promotion_df = pd.read_csv('./data/promotion_df.csv')
merged_df = pd.read_csv('./data/all_merged.csv')

In [ ]:
# amount 기준으로 difficulty를 못 넘는 정상 completed 행 수
raw_under_diff = promotion_df[
    (promotion_df['is_completed'].eq(1)) &
    (promotion_df['is_normal_flow'].eq(1)) &
    (promotion_df['amount'] < promotion_df['difficulty'])
].copy()

print('amount_raw 기준 difficulty 미달 건수:', len(raw_under_diff))

amount_raw 기준 difficulty 미달 건수: 3301

In [38]:
transactions = merged_df[merged_df['event'] == 'transaction'].copy()
transactions = transactions[['person', 'time', 'amount']]
transactions = transactions.sort_values(['person', 'time']).reset_index(drop=True)

views = merged_df[merged_df['event'] == 'offer viewed'].copy()
views = views[['person', 'offer_id', 'time']]
views = views.sort_values(['person', 'offer_id', 'time']).reset_index(drop=True)

tx_by_person = {}
for _, row in transactions.iterrows():
    person = row['person']
    if person not in tx_by_person:
        tx_by_person[person] = []
    tx_by_person[person].append((row['time'], row['amount']))

view_by_person_offer = {}
for _, row in views.iterrows():
    key = (row['person'], row['offer_id'])
    if key not in view_by_person_offer:
        view_by_person_offer[key] = []
    view_by_person_offer[key].append(row['time'])

In [39]:
promotion_df = promotion_df.sort_values(
    ['person', 'offer_id', 'offer received', 'offer completed']
).reset_index(drop=True)

In [40]:
completion_amount_current_list = []

for _, row in promotion_df.iterrows():
    person = row['person']
    start_time = row['offer received']
    end_time = row['offer completed']

    total = 0.0
    if person in tx_by_person:
        for tx_time, amount in tx_by_person[person]:
            if tx_time >= start_time and tx_time <= end_time:
                total += amount

    completion_amount_current_list.append(round(total, 2))

promotion_df['completion_amount_current'] = completion_amount_current_list

In [44]:
promo_influenced_amount_list = []

for _, row in promotion_df.iterrows():
    person = row['person']
    viewed_time = row['offer viewed']
    end_time = row['offer completed']

    if pd.isna(viewed_time):
        promo_influenced_amount_list.append(np.nan)
        continue

    total = 0.0
    if person in tx_by_person:
        for tx_time, amount in tx_by_person[person]:
            if tx_time >= viewed_time and tx_time <= end_time:
                total += amount

    promo_influenced_amount_list.append(round(total, 2))

promotion_df['promo_influenced_amount'] = promo_influenced_amount_list

In [45]:
anomaly = promotion_df[
    (promotion_df['is_completed'].eq(1)) &
    (promotion_df['is_normal_flow'].eq(1)) &
    (promotion_df['completion_amount_current'] < promotion_df['difficulty'])
].copy()

print('anomaly 행 수:', len(anomaly))

anomaly 행 수: 76

In [46]:
prev_helper = promotion_df[
    ['person', 'offer_id', 'offer_cycle', 'offer received']
].copy()

prev_helper = prev_helper.sort_values(
    ['person', 'offer_id', 'offer received']
).reset_index(drop=True)

prev_helper['prev_received'] = prev_helper.groupby(['person', 'offer_id'])['offer received'].shift(1)

anomaly = anomaly.drop(columns=['prev_received'], errors='ignore')

anomaly = anomaly.merge(
    prev_helper[['person', 'offer_id', 'offer_cycle', 'prev_received']],
    on=['person', 'offer_id', 'offer_cycle'],
    how='left'
)

In [47]:
completion_amount_prev_received_list = []

for _, row in anomaly.iterrows():
    person = row['person']
    start_time = row['prev_received']
    end_time = row['offer completed']

    if pd.isna(start_time):
        completion_amount_prev_received_list.append(np.nan)
        continue

    total = 0.0
    if person in tx_by_person:
        for tx_time, amount in tx_by_person[person]:
            if tx_time >= start_time and tx_time <= end_time:
                total += amount

    completion_amount_prev_received_list.append(round(total, 2))

anomaly['completion_amount_prev_received'] = completion_amount_prev_received_list

In [48]:
prev_viewed_list = []
promo_influenced_amount_prev_received_list = []

for _, row in anomaly.iterrows():
    person = row['person']
    offer_id = row['offer_id']
    prev_received = row['prev_received']
    end_time = row['offer completed']

    prev_viewed = np.nan
    total = 0.0

    if pd.notna(prev_received):
        key = (person, offer_id)
        if key in view_by_person_offer:
            for view_time in view_by_person_offer[key]:
                if view_time >= prev_received and view_time <= end_time:
                    prev_viewed = view_time
                    break

        if pd.notna(prev_viewed) and person in tx_by_person:
            for tx_time, amount in tx_by_person[person]:
                if tx_time >= prev_viewed and tx_time <= end_time:
                    total += amount

    prev_viewed_list.append(prev_viewed)
    if pd.isna(prev_viewed):
        promo_influenced_amount_prev_received_list.append(np.nan)
    else:
        promo_influenced_amount_prev_received_list.append(round(total, 2))

anomaly['prev_viewed'] = prev_viewed_list
anomaly['promo_influenced_amount_prev_received'] = promo_influenced_amount_prev_received_list

In [51]:
promotion_df = promotion_df.drop(columns=['completion_amount_prev_received'], errors='ignore')

promotion_df = promotion_df.merge(
    anomaly[
        [
            'person', 'offer_id', 'offer_cycle',
            'prev_received',
            'completion_amount_prev_received',
            'prev_viewed',
            'promo_influenced_amount_prev_received'
        ]
    ],
    on=['person', 'offer_id', 'offer_cycle'],
    how='left'
)

In [52]:
promotion_df['adjusted_completion_amount'] = promotion_df['completion_amount_current']

fix_mask = promotion_df['completion_amount_prev_received'].ge(promotion_df['difficulty'])
promotion_df.loc[fix_mask, 'adjusted_completion_amount'] = promotion_df.loc[fix_mask, 'completion_amount_prev_received']

In [53]:
display(
    promotion_df[
        [
            'person', 'offer_id', 'offer_cycle',
            'offer received', 'prev_received',
            'offer viewed', 'prev_viewed',
            'offer completed', 'difficulty',
            'completion_amount_current',
            'completion_amount_prev_received',
            'promo_influenced_amount',
            'promo_influenced_amount_prev_received',
            'adjusted_completion_amount'
        ]
    ].head(20)
)

,person,offer_id,offer_cycle,offer received,prev_received,offer viewed,prev_viewed,offer completed,difficulty,completion_amount_current,completion_amount_prev_received,promo_influenced_amount,promo_influenced_amount_prev_received,adjusted_completion_amount
0,0009655768c64bdeb2e877511632db8f,bogo_5_5_5,Bogo_1,408.0,NaN,456.0,NaN,414.0,5,8.57,NaN,0.00,NaN,8.57
1,0009655768c64bdeb2e877511632db8f,discount_10_2_10,Discount_1,504.0,NaN,540.0,NaN,528.0,10,14.11,NaN,0.00,NaN,14.11
2,0009655768c64bdeb2e877511632db8f,discount_10_2_7,Discount_1,576.0,NaN,NaN,NaN,576.0,10,10.27,NaN,NaN,NaN,10.27
3,0009655768c64bdeb2e877511632db8f,informational_0_0_3,Informational_1,168.0,NaN,192.0,NaN,NaN,0,0.00,NaN,0.00,NaN,0.00
4,0009655768c64bdeb2e877511632db8f,informational_0_0_4,Informational_1,336.0,NaN,372.0,NaN,NaN,0,0.00,NaN,0.00,NaN,0.00
5,00116118485d4dfda04fdbaba9a87b5c,bogo_5_5_5,Bogo_1,168.0,NaN,216.0,NaN,NaN,5,0.00,NaN,0.00,NaN,0.00
6,00116118485d4dfda04fdbaba9a87b5c,bogo_5_5_5,Bogo_2,576.0,NaN,630.0,NaN,NaN,5,0.00,NaN,0.00,NaN,0.00
7,0011e0d4e6b944f998e987f904e8c1e5,bogo_5_5_7,Bogo_1,504.0,NaN,516.0,NaN,576.0,5,22.05,NaN,22.05,NaN,22.05
8,0011e0d4e6b944f998e987f904e8c1e5,discount_20_5_10,Discount_1,408.0,NaN,432.0,NaN,576.0,20,22.05,NaN,22.05,NaN,22.05
9,0011e0d4e6b944f998e987f904e8c1e5,discount_7_3_7,Discount_1,168.0,NaN,186.0,NaN,252.0,7,11.93,NaN,11.93,NaN,11.93
10,0011e0d4e6b944f998e987f904e8c1e5,informational_0_0_3,Informational_1,336.0,NaN,354.0,NaN,NaN,0,0.00,NaN,0.00,NaN,0.00
11,0011e0d4e6b944f998e987f904e8c1e5,informational_0_0_4,Informational_1,0.0,NaN,6.0,NaN,NaN,0,0.00,NaN,0.00,NaN,0.00
12,0020c2b971eb4e9188eac86d93036a77,bogo_10_10_5,Bogo_1,408.0,NaN,426.0,NaN,510.0,10,17.24,NaN,17.24,NaN,17.24
13,0020c2b971eb4e9188eac86d93036a77,bogo_10_10_7,Bogo_1,168.0,NaN,NaN,NaN,NaN,10,0.00,NaN,NaN,NaN,0.00
14,0020c2b971eb4e9188eac86d93036a77,discount_10_2_10,Discount_1,0.0,NaN,12.0,NaN,54.0,10,17.63,NaN,17.63,NaN,17.63
15,0020c2b971eb4e9188eac86d93036a77,discount_10_2_10,Discount_2,336.0,NaN,NaN,NaN,510.0,10,17.24,NaN,NaN,NaN,17.24
16,0020c2b971eb4e9188eac86d93036a77,informational_0_0_3,Informational_1,504.0,NaN,660.0,NaN,NaN,0,0.00,NaN,0.00,NaN,0.00
17,0020ccbbb6d84e358d3414a3ff76cffd,bogo_5_5_5,Bogo_1,336.0,NaN,348.0,NaN,378.0,5,14.53,NaN,14.53,NaN,14.53
18,0020ccbbb6d84e358d3414a3ff76cffd,bogo_5_5_7,Bogo_1,504.0,NaN,582.0,NaN,600.0,5,10.32,NaN,10.32,NaN,10.32
19,0020ccbbb6d84e358d3414a3ff76cffd,discount_7_3_7,Discount_1,168.0,NaN,168.0,NaN,222.0,7,11.65,NaN,11.65,NaN,11.65

In [54]:
remain = promotion_df[
    (promotion_df['is_completed'].eq(1)) &
    (promotion_df['is_normal_flow'].eq(1)) &
    (promotion_df['adjusted_completion_amount'] < promotion_df['difficulty'])
].copy()

print('여전히 difficulty보다 작은 정상 completed 건수:', len(remain))

여전히 difficulty보다 작은 정상 completed 건수: 0

In [55]:
promotion_final = promotion_df.copy()

# 원래 amount는 보관
promotion_final['amount_raw'] = promotion_final['amount']

# 최종 amount는 보정값으로 교체
promotion_final['amount'] = promotion_final['adjusted_completion_amount']

In [56]:
# promo 영향액도 최종값으로 정리
promotion_final['promo_influenced_amount_final'] = promotion_final['promo_influenced_amount']

mask = promotion_final['completion_amount_current'] < promotion_final['difficulty']
promotion_final.loc[mask, 'promo_influenced_amount_final'] = \
    promotion_final.loc[mask, 'promo_influenced_amount_prev_received']

In [57]:
promotion_final.head(20)

,person,offer_id,offer_cycle,offer received,offer viewed,offer completed,offer_type,difficulty,reward,duration,...,is_deduplicated,completion_amount_current,promo_influenced_amount,prev_received,completion_amount_prev_received,prev_viewed,promo_influenced_amount_prev_received,adjusted_completion_amount,amount_raw,promo_influenced_amount_final
0,0009655768c64bdeb2e877511632db8f,bogo_5_5_5,Bogo_1,408.0,456.0,414.0,bogo,5,5,5,...,0,8.57,0.00,NaN,NaN,NaN,NaN,8.57,8.57,0.00
1,0009655768c64bdeb2e877511632db8f,discount_10_2_10,Discount_1,504.0,540.0,528.0,discount,10,2,10,...,0,14.11,0.00,NaN,NaN,NaN,NaN,14.11,14.11,0.00
2,0009655768c64bdeb2e877511632db8f,discount_10_2_7,Discount_1,576.0,NaN,576.0,discount,10,2,7,...,0,10.27,NaN,NaN,NaN,NaN,NaN,10.27,10.27,NaN
3,0009655768c64bdeb2e877511632db8f,informational_0_0_3,Informational_1,168.0,192.0,NaN,informational,0,0,3,...,0,0.00,0.00,NaN,NaN,NaN,NaN,0.00,NaN,0.00
4,0009655768c64bdeb2e877511632db8f,informational_0_0_4,Informational_1,336.0,372.0,NaN,informational,0,0,4,...,0,0.00,0.00,NaN,NaN,NaN,NaN,0.00,NaN,0.00
5,00116118485d4dfda04fdbaba9a87b5c,bogo_5_5_5,Bogo_1,168.0,216.0,NaN,bogo,5,5,5,...,0,0.00,0.00,NaN,NaN,NaN,NaN,0.00,NaN,NaN
6,00116118485d4dfda04fdbaba9a87b5c,bogo_5_5_5,Bogo_2,576.0,630.0,NaN,bogo,5,5,5,...,0,0.00,0.00,NaN,NaN,NaN,NaN,0.00,NaN,NaN
7,0011e0d4e6b944f998e987f904e8c1e5,bogo_5_5_7,Bogo_1,504.0,516.0,576.0,bogo,5,5,7,...,1,22.05,22.05,NaN,NaN,NaN,NaN,22.05,22.05,22.05
8,0011e0d4e6b944f998e987f904e8c1e5,discount_20_5_10,Discount_1,408.0,432.0,576.0,discount,20,5,10,...,0,22.05,22.05,NaN,NaN,NaN,NaN,22.05,22.05,22.05
9,0011e0d4e6b944f998e987f904e8c1e5,discount_7_3_7,Discount_1,168.0,186.0,252.0,discount,7,3,7,...,1,11.93,11.93,NaN,NaN,NaN,NaN,11.93,11.93,11.93
10,0011e0d4e6b944f998e987f904e8c1e5,informational_0_0_3,Informational_1,336.0,354.0,NaN,informational,0,0,3,...,0,0.00,0.00,NaN,NaN,NaN,NaN,0.00,NaN,0.00
11,0011e0d4e6b944f998e987f904e8c1e5,informational_0_0_4,Informational_1,0.0,6.0,NaN,informational,0,0,4,...,0,0.00,0.00,NaN,NaN,NaN,NaN,0.00,NaN,0.00
12,0020c2b971eb4e9188eac86d93036a77,bogo_10_10_5,Bogo_1,408.0,426.0,510.0,bogo,10,10,5,...,1,17.24,17.24,NaN,NaN,NaN,NaN,17.24,17.24,17.24
13,0020c2b971eb4e9188eac86d93036a77,bogo_10_10_7,Bogo_1,168.0,NaN,NaN,bogo,10,10,7,...,0,0.00,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN
14,0020c2b971eb4e9188eac86d93036a77,discount_10_2_10,Discount_1,0.0,12.0,54.0,discount,10,2,10,...,1,17.63,17.63,NaN,NaN,NaN,NaN,17.63,17.63,17.63
15,0020c2b971eb4e9188eac86d93036a77,discount_10_2_10,Discount_2,336.0,NaN,510.0,discount,10,2,10,...,0,17.24,NaN,NaN,NaN,NaN,NaN,17.24,17.24,NaN
16,0020c2b971eb4e9188eac86d93036a77,informational_0_0_3,Informational_1,504.0,660.0,NaN,informational,0,0,3,...,0,0.00,0.00,NaN,NaN,NaN,NaN,0.00,NaN,0.00
17,0020ccbbb6d84e358d3414a3ff76cffd,bogo_5_5_5,Bogo_1,336.0,348.0,378.0,bogo,5,5,5,...,1,14.53,14.53,NaN,NaN,NaN,NaN,14.53,14.53,14.53
18,0020ccbbb6d84e358d3414a3ff76cffd,bogo_5_5_7,Bogo_1,504.0,582.0,600.0,bogo,5,5,7,...,1,10.32,10.32,NaN,NaN,NaN,NaN,10.32,10.32,10.32
19,0020ccbbb6d84e358d3414a3ff76cffd,discount_7_3_7,Discount_1,168.0,168.0,222.0,discount,7,3,7,...,1,11.65,11.65,NaN,NaN,NaN,NaN,11.65,11.65,11.65

In [58]:
# # 저장
# promotion_final.to_csv('./data/promotion_final.csv', index=False)

In [ ]:
# # 76건 각각에 대해 received 전후 타임라인 확인
# for _, row in anomaly.sort_values(['person', 'offer_id', 'offer received']).iterrows():
#     person = row['person']
#     offer_id = row['offer_id']
#     start = row['prev_received'] if pd.notna(row['prev_received']) else row['offer received']
#     end = row['offer completed']


#     print(f"\n### person={person}, offer_id={offer_id}, offer_cycle={row['offer_cycle']}")
#     print(f"current received: {row['offer received']}, prev received: {row['prev_received']}, completed: {row['offer completed']}")

#     window = merged_df[
#         (merged_df['person'] == person) &
#         (merged_df['time'] >= start) &
#         (merged_df['time'] <= end)
#     ].sort_values(['time', 'Unnamed: 0'])

#     display(window[['time', 'event', 'amount', 'offer_id', 'offer_type', 'difficulty', 'duration']])

### person=04369aa7ac9a4440a794c471ae7c3f77, offer_id=discount_7_3_7, offer_cycle=Discount_2
current received: 576.0, prev received: 504.0, completed: 636.0

,time,event,amount,offer_id,offer_type,difficulty,duration
4860,504,offer received,NaN,discount_7_3_7,discount,7.0,7.0
4861,504,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
4862,504,transaction,2.13,NaN,NaN,NaN,NaN
4863,576,offer received,NaN,discount_7_3_7,discount,7.0,7.0
4864,576,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
4865,636,transaction,5.06,NaN,NaN,NaN,NaN
4866,636,offer completed,NaN,discount_7_3_7,discount,7.0,7.0

### person=072290a7410e49d3a1e45a89c92c58f3, offer_id=discount_7_3_7, offer_cycle=Discount_2
current received: 408.0, prev received: 336.0, completed: 432.0

,time,event,amount,offer_id,offer_type,difficulty,duration
8300,336,offer received,NaN,discount_7_3_7,discount,7.0,7.0
8301,336,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
8302,342,transaction,3.58,NaN,NaN,NaN,NaN
8303,360,transaction,1.04,NaN,NaN,NaN,NaN
8304,372,transaction,1.12,NaN,NaN,NaN,NaN
8305,408,offer received,NaN,discount_7_3_7,discount,7.0,7.0
8306,414,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
8307,432,transaction,2.29,NaN,NaN,NaN,NaN
8308,432,offer completed,NaN,discount_7_3_7,discount,7.0,7.0

### person=09e7e40eb89943458f4f79fe2e023dd6, offer_id=discount_7_3_7, offer_cycle=Discount_2
current received: 576.0, prev received: 504.0, completed: 606.0

,time,event,amount,offer_id,offer_type,difficulty,duration
11628,504,offer received,NaN,discount_7_3_7,discount,7.0,7.0
11629,504,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
11630,540,transaction,6.19,NaN,NaN,NaN,NaN
11631,576,offer received,NaN,discount_7_3_7,discount,7.0,7.0
11632,576,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
11633,606,transaction,2.01,NaN,NaN,NaN,NaN
11634,606,offer completed,NaN,discount_7_3_7,discount,7.0,7.0

### person=0b6b453772ea4c3a963e92ae2b0817a2, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 576.0, prev received: 408.0, completed: 642.0

,time,event,amount,offer_id,offer_type,difficulty,duration
13580,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
13581,426,transaction,0.95,NaN,NaN,NaN,NaN
13582,444,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
13583,504,offer received,NaN,discount_10_2_7,discount,10.0,7.0
13584,564,transaction,2.18,NaN,NaN,NaN,NaN
13585,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
13586,588,transaction,2.28,NaN,NaN,NaN,NaN
13587,600,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
13588,600,transaction,3.30,NaN,NaN,NaN,NaN
13589,642,transaction,2.18,NaN,NaN,NaN,NaN
13590,642,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=0c57fbefe3fd4fdf8c275ed3da65f871, offer_id=discount_10_2_10, offer_cycle=Discount_3
current received: 576.0, prev received: 504.0, completed: 672.0

,time,event,amount,offer_id,offer_type,difficulty,duration
14692,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
14693,516,transaction,5.94,NaN,NaN,NaN,NaN
14694,528,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
14695,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
14696,606,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
14697,648,transaction,2.98,NaN,NaN,NaN,NaN
14698,672,transaction,1.32,NaN,NaN,NaN,NaN
14699,672,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=1303cccd542e4e63af9e04f2587e6261, offer_id=discount_10_2_7, offer_cycle=Discount_2
current received: 408.0, prev received: 336.0, completed: 486.0

,time,event,amount,offer_id,offer_type,difficulty,duration
22266,336,offer received,NaN,discount_10_2_7,discount,10.0,7.0
22267,342,transaction,4.79,NaN,NaN,NaN,NaN
22268,408,offer received,NaN,discount_10_2_7,discount,10.0,7.0
22269,408,offer viewed,NaN,discount_10_2_7,discount,10.0,7.0
22270,426,transaction,1.13,NaN,NaN,NaN,NaN
22271,444,transaction,1.47,NaN,NaN,NaN,NaN
22272,486,transaction,4.89,NaN,NaN,NaN,NaN
22273,486,offer completed,NaN,discount_10_2_7,discount,10.0,7.0

### person=14cd68209b934834afcbc6f217ddde0a, offer_id=discount_10_2_7, offer_cycle=Discount_2
current received: 408.0, prev received: 336.0, completed: 450.0

,time,event,amount,offer_id,offer_type,difficulty,duration
24502,336,offer received,NaN,discount_10_2_7,discount,10.0,7.0
24503,348,transaction,5.03,NaN,NaN,NaN,NaN
24504,378,transaction,2.17,NaN,NaN,NaN,NaN
24505,408,offer received,NaN,discount_10_2_7,discount,10.0,7.0
24506,426,offer viewed,NaN,discount_10_2_7,discount,10.0,7.0
24507,432,transaction,0.48,NaN,NaN,NaN,NaN
24508,450,transaction,2.45,NaN,NaN,NaN,NaN
24509,450,offer completed,NaN,discount_10_2_7,discount,10.0,7.0

### person=18cc6dbe8e124c20b7bc93c39e854cdd, offer_id=discount_20_5_10, offer_cycle=Discount_2
current received: 408.0, prev received: 336.0, completed: 486.0

,time,event,amount,offer_id,offer_type,difficulty,duration
28853,336,offer received,NaN,discount_20_5_10,discount,20.0,10.0
28854,396,transaction,18.57,NaN,NaN,NaN,NaN
28855,408,offer received,NaN,discount_20_5_10,discount,20.0,10.0
28856,414,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
28857,486,transaction,12.63,NaN,NaN,NaN,NaN
28858,486,offer completed,NaN,discount_20_5_10,discount,20.0,10.0

### person=1b24e887d980450497b631d8756128e6, offer_id=discount_10_2_7, offer_cycle=Discount_2
current received: 576.0, prev received: 504.0, completed: 660.0

,time,event,amount,offer_id,offer_type,difficulty,duration
31608,504,offer received,NaN,discount_10_2_7,discount,10.0,7.0
31609,510,transaction,7.09,NaN,NaN,NaN,NaN
31610,576,offer received,NaN,discount_10_2_7,discount,10.0,7.0
31611,630,offer viewed,NaN,discount_10_2_7,discount,10.0,7.0
31612,660,transaction,3.34,NaN,NaN,NaN,NaN
31613,660,offer completed,NaN,discount_10_2_7,discount,10.0,7.0

### person=1cf24c771801476294824c4387196508, offer_id=discount_7_3_7, offer_cycle=Discount_2
current received: 408.0, prev received: 336.0, completed: 420.0

,time,event,amount,offer_id,offer_type,difficulty,duration
33568,336,offer received,NaN,discount_7_3_7,discount,7.0,7.0
33569,342,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
33570,366,transaction,0.72,NaN,NaN,NaN,NaN
33571,384,transaction,1.08,NaN,NaN,NaN,NaN
33572,396,transaction,3.05,NaN,NaN,NaN,NaN
33573,408,offer received,NaN,discount_7_3_7,discount,7.0,7.0
33574,420,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
33575,420,transaction,3.96,NaN,NaN,NaN,NaN
33576,420,offer completed,NaN,discount_7_3_7,discount,7.0,7.0

### person=1d02e70963a6471c9fe05962b0766d32, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 504.0, prev received: 408.0, completed: 636.0

,time,event,amount,offer_id,offer_type,difficulty,duration
33653,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
33654,408,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
33655,444,transaction,4.93,NaN,NaN,NaN,NaN
33656,462,transaction,0.27,NaN,NaN,NaN,NaN
33657,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
33658,510,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
33659,546,transaction,0.99,NaN,NaN,NaN,NaN
33660,570,transaction,0.54,NaN,NaN,NaN,NaN
33661,576,offer received,NaN,informational_0_0_3,informational,0.0,3.0
33662,576,offer viewed,NaN,informational_0_0_3,informational,0.0,3.0
33663,630,transaction,0.55,NaN,NaN,NaN,NaN
33664,636,transaction,4.68,NaN,NaN,NaN,NaN
33665,636,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=1fc3062abe934ba3b6744ea281ef4696, offer_id=discount_20_5_10, offer_cycle=Discount_2
current received: 504.0, prev received: 336.0, completed: 576.0

,time,event,amount,offer_id,offer_type,difficulty,duration
36889,336,offer received,NaN,discount_20_5_10,discount,20.0,10.0
36890,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
36891,420,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
36892,492,transaction,10.31,NaN,NaN,NaN,NaN
36893,492,offer completed,NaN,discount_10_2_10,discount,10.0,10.0
36894,504,offer received,NaN,discount_20_5_10,discount,20.0,10.0
36895,516,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
36896,576,transaction,15.32,NaN,NaN,NaN,NaN
36897,576,offer completed,NaN,discount_20_5_10,discount,20.0,10.0

### person=23ce738b421d4731a8f8c09dea537aea, offer_id=discount_10_2_7, offer_cycle=Discount_2
current received: 576.0, prev received: 504.0, completed: 630.0

,time,event,amount,offer_id,offer_type,difficulty,duration
41274,504,offer received,NaN,discount_10_2_7,discount,10.0,7.0
41275,504,transaction,3.95,NaN,NaN,NaN,NaN
41276,552,transaction,4.49,NaN,NaN,NaN,NaN
41277,558,offer viewed,NaN,discount_10_2_7,discount,10.0,7.0
41278,576,offer received,NaN,discount_10_2_7,discount,10.0,7.0
41279,594,offer viewed,NaN,discount_10_2_7,discount,10.0,7.0
41280,630,transaction,4.13,NaN,NaN,NaN,NaN
41281,630,offer completed,NaN,discount_10_2_7,discount,10.0,7.0

### person=26fcd3c2c294477ea0cca9c5906850df, offer_id=discount_20_5_10, offer_cycle=Discount_3
current received: 504.0, prev received: 408.0, completed: 618.0

,time,event,amount,offer_id,offer_type,difficulty,duration
45115,408,offer received,NaN,discount_20_5_10,discount,20.0,10.0
45116,444,transaction,1.06,NaN,NaN,NaN,NaN
45117,498,transaction,5.51,NaN,NaN,NaN,NaN
45118,504,offer received,NaN,discount_20_5_10,discount,20.0,10.0
45119,546,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
45120,546,transaction,1.65,NaN,NaN,NaN,NaN
45121,552,transaction,3.76,NaN,NaN,NaN,NaN
45122,576,transaction,0.95,NaN,NaN,NaN,NaN
45123,588,transaction,2.75,NaN,NaN,NaN,NaN
45124,600,transaction,2.65,NaN,NaN,NaN,NaN
45125,618,transaction,2.67,NaN,NaN,NaN,NaN
45126,618,offer completed,NaN,discount_20_5_10,discount,20.0,10.0

### person=2ac20da42e704b4bae0a799018096259, offer_id=discount_7_3_7, offer_cycle=Discount_2
current received: 408.0, prev received: 336.0, completed: 456.0

,time,event,amount,offer_id,offer_type,difficulty,duration
49393,336,offer received,NaN,discount_7_3_7,discount,7.0,7.0
49394,378,transaction,6.60,NaN,NaN,NaN,NaN
49395,408,offer received,NaN,discount_7_3_7,discount,7.0,7.0
49396,444,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
49397,456,transaction,0.59,NaN,NaN,NaN,NaN
49398,456,offer completed,NaN,discount_7_3_7,discount,7.0,7.0

### person=2c4fbcf0ef95498f923f7c7424dc4839, offer_id=discount_10_2_7, offer_cycle=Discount_2
current received: 504.0, prev received: 408.0, completed: 516.0

,time,event,amount,offer_id,offer_type,difficulty,duration
51472,408,offer received,NaN,discount_10_2_7,discount,10.0,7.0
51473,408,offer viewed,NaN,discount_10_2_7,discount,10.0,7.0
51474,426,transaction,0.28,NaN,NaN,NaN,NaN
51475,432,transaction,4.75,NaN,NaN,NaN,NaN
51476,456,transaction,2.09,NaN,NaN,NaN,NaN
51477,504,offer received,NaN,discount_10_2_7,discount,10.0,7.0
51478,504,offer viewed,NaN,discount_10_2_7,discount,10.0,7.0
51479,516,transaction,3.68,NaN,NaN,NaN,NaN
51480,516,offer completed,NaN,discount_10_2_7,discount,10.0,7.0

### person=2cad48dcddc44f9dac43c2d9b476535b, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 576.0, prev received: 504.0, completed: 636.0

,time,event,amount,offer_id,offer_type,difficulty,duration
52203,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
52204,522,transaction,3.08,NaN,NaN,NaN,NaN
52205,540,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
52206,558,transaction,1.84,NaN,NaN,NaN,NaN
52207,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
52208,576,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
52209,600,transaction,0.46,NaN,NaN,NaN,NaN
52210,624,transaction,0.85,NaN,NaN,NaN,NaN
52211,636,transaction,4.69,NaN,NaN,NaN,NaN
52212,636,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=2ea50de315514ccaa5079db4c1ecbc0b, offer_id=discount_10_2_10, offer_cycle=Discount_4
current received: 504.0, prev received: 408.0, completed: 528.0

,time,event,amount,offer_id,offer_type,difficulty,duration
54962,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
54963,420,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
54964,450,transaction,5.00,NaN,NaN,NaN,NaN
54965,462,transaction,4.08,NaN,NaN,NaN,NaN
54966,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
54967,504,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
54968,528,transaction,2.55,NaN,NaN,NaN,NaN
54969,528,offer completed,NaN,discount_10_2_10,discount,10.0,10.0
54970,528,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=2ea50de315514ccaa5079db4c1ecbc0b, offer_id=discount_10_2_10, offer_cycle=Discount_5
current received: 576.0, prev received: 504.0, completed: 666.0

,time,event,amount,offer_id,offer_type,difficulty,duration
54966,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
54967,504,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
54968,528,transaction,2.55,NaN,NaN,NaN,NaN
54969,528,offer completed,NaN,discount_10_2_10,discount,10.0,10.0
54970,528,offer completed,NaN,discount_10_2_10,discount,10.0,10.0
54971,552,transaction,2.02,NaN,NaN,NaN,NaN
54972,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
54973,576,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
54974,666,transaction,5.94,NaN,NaN,NaN,NaN
54975,666,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=3339d9d8f5ff4664bd259572330c5dbf, offer_id=discount_7_3_7, offer_cycle=Discount_2
current received: 408.0, prev received: 336.0, completed: 444.0

,time,event,amount,offer_id,offer_type,difficulty,duration
60935,336,offer received,NaN,discount_7_3_7,discount,7.0,7.0
60936,342,transaction,4.65,NaN,NaN,NaN,NaN
60937,354,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
60938,372,transaction,0.09,NaN,NaN,NaN,NaN
60939,378,transaction,1.50,NaN,NaN,NaN,NaN
60940,378,offer completed,NaN,discount_10_2_10,discount,10.0,10.0
60941,408,offer received,NaN,discount_7_3_7,discount,7.0,7.0
60942,420,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
60943,432,transaction,0.51,NaN,NaN,NaN,NaN
60944,444,transaction,3.72,NaN,NaN,NaN,NaN
60945,444,offer completed,NaN,discount_7_3_7,discount,7.0,7.0

### person=37a286492a574090a662386d13968cd2, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 504.0, prev received: 408.0, completed: 540.0

,time,event,amount,offer_id,offer_type,difficulty,duration
66008,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
66009,420,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
66010,498,transaction,4.05,NaN,NaN,NaN,NaN
66011,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
66012,504,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
66013,540,transaction,9.00,NaN,NaN,NaN,NaN
66014,540,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=3d55f046a320408db9a88be59acc19cc, offer_id=discount_10_2_10, offer_cycle=Discount_3
current received: 576.0, prev received: 408.0, completed: 600.0

,time,event,amount,offer_id,offer_type,difficulty,duration
73766,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
73767,438,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
73768,438,transaction,2.92,NaN,NaN,NaN,NaN
73769,444,transaction,0.58,NaN,NaN,NaN,NaN
73770,462,transaction,0.44,NaN,NaN,NaN,NaN
73771,480,transaction,1.15,NaN,NaN,NaN,NaN
73772,504,offer received,NaN,discount_10_2_7,discount,10.0,7.0
73773,522,transaction,3.53,NaN,NaN,NaN,NaN
73774,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
73775,576,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
73776,600,transaction,2.59,NaN,NaN,NaN,NaN
73777,600,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=3db080837a5f4137aeb5cab01f739866, offer_id=discount_10_2_7, offer_cycle=Discount_4
current received: 576.0, prev received: 504.0, completed: 600.0

,time,event,amount,offer_id,offer_type,difficulty,duration
74254,504,offer received,NaN,discount_10_2_7,discount,10.0,7.0
74255,504,offer viewed,NaN,discount_10_2_7,discount,10.0,7.0
74256,540,transaction,3.79,NaN,NaN,NaN,NaN
74257,570,transaction,1.56,NaN,NaN,NaN,NaN
74258,576,offer received,NaN,discount_10_2_7,discount,10.0,7.0
74259,576,transaction,0.71,NaN,NaN,NaN,NaN
74260,582,offer viewed,NaN,discount_10_2_7,discount,10.0,7.0
74261,588,transaction,3.45,NaN,NaN,NaN,NaN
74262,600,transaction,0.60,NaN,NaN,NaN,NaN
74263,600,offer completed,NaN,discount_10_2_7,discount,10.0,7.0

### person=4150dd859f444e338eadb7e570a0e183, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 504.0, prev received: 408.0, completed: 570.0

,time,event,amount,offer_id,offer_type,difficulty,duration
78447,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
78448,414,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
78449,498,transaction,7.80,NaN,NaN,NaN,NaN
78450,498,offer completed,NaN,discount_10_2_7,discount,10.0,7.0
78451,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
78452,534,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
78453,546,transaction,1.25,NaN,NaN,NaN,NaN
78454,570,transaction,2.46,NaN,NaN,NaN,NaN
78455,570,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=4178b9ae5e874f48b27514bf09f1437c, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 576.0, prev received: 504.0, completed: 666.0

,time,event,amount,offer_id,offer_type,difficulty,duration
78676,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
78677,510,transaction,1.64,NaN,NaN,NaN,NaN
78678,534,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
78679,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
78680,588,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
78681,648,transaction,5.65,NaN,NaN,NaN,NaN
78682,666,transaction,2.94,NaN,NaN,NaN,NaN
78683,666,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=47360ba339474b9695398e4fe56773bd, offer_id=discount_20_5_10, offer_cycle=Discount_3
current received: 336.0, prev received: 168.0, completed: 360.0

,time,event,amount,offer_id,offer_type,difficulty,duration
85785,168,offer received,NaN,discount_20_5_10,discount,20.0,10.0
85786,192,transaction,7.99,NaN,NaN,NaN,NaN
85787,294,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
85788,336,offer received,NaN,discount_20_5_10,discount,20.0,10.0
85789,360,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
85790,360,transaction,19.77,NaN,NaN,NaN,NaN
85791,360,offer completed,NaN,discount_20_5_10,discount,20.0,10.0

### person=47e7f9c17bbe4562b6e85b8136a1c9a0, offer_id=discount_20_5_10, offer_cycle=Discount_2
current received: 408.0, prev received: 336.0, completed: 492.0

,time,event,amount,offer_id,offer_type,difficulty,duration
86609,336,offer received,NaN,discount_20_5_10,discount,20.0,10.0
86610,342,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
86611,366,transaction,7.68,NaN,NaN,NaN,NaN
86612,402,transaction,2.02,NaN,NaN,NaN,NaN
86613,408,offer received,NaN,discount_20_5_10,discount,20.0,10.0
86614,432,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
86615,444,transaction,3.77,NaN,NaN,NaN,NaN
86616,474,transaction,3.35,NaN,NaN,NaN,NaN
86617,492,transaction,4.15,NaN,NaN,NaN,NaN
86618,492,offer completed,NaN,discount_20_5_10,discount,20.0,10.0

### person=4a74c87b845e49b7b73a2674e09798e5, offer_id=discount_7_3_7, offer_cycle=Discount_3
current received: 504.0, prev received: 408.0, completed: 576.0

,time,event,amount,offer_id,offer_type,difficulty,duration
89433,408,offer received,NaN,discount_7_3_7,discount,7.0,7.0
89434,474,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
89435,486,transaction,4.15,NaN,NaN,NaN,NaN
89436,504,offer received,NaN,discount_7_3_7,discount,7.0,7.0
89437,570,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
89438,576,transaction,2.87,NaN,NaN,NaN,NaN
89439,576,offer completed,NaN,discount_7_3_7,discount,7.0,7.0

### person=4d81f9f887724401a9c7606db4afef01, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 168.0, prev received: 0.0, completed: 204.0

,time,event,amount,offer_id,offer_type,difficulty,duration
93141,0,offer received,NaN,discount_10_2_10,discount,10.0,10.0
93142,12,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
93143,36,transaction,6.99,NaN,NaN,NaN,NaN
93144,96,transaction,0.85,NaN,NaN,NaN,NaN
93145,150,transaction,1.23,NaN,NaN,NaN,NaN
93146,168,offer received,NaN,discount_10_2_10,discount,10.0,10.0
93147,186,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
93148,204,transaction,2.11,NaN,NaN,NaN,NaN
93149,204,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=4e3fa85725f141f6b4bf3bae3a485986, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 504.0, prev received: 408.0, completed: 576.0

,time,event,amount,offer_id,offer_type,difficulty,duration
93985,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
93986,456,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
93987,468,transaction,5.70,NaN,NaN,NaN,NaN
93988,468,offer completed,NaN,bogo_5_5_7,bogo,5.0,7.0
93989,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
93990,510,transaction,1.09,NaN,NaN,NaN,NaN
93991,528,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
93992,534,transaction,1.72,NaN,NaN,NaN,NaN
93993,576,transaction,3.79,NaN,NaN,NaN,NaN
93994,576,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=4e6bba79666b414f933e0a2b25bf17bd, offer_id=discount_20_5_10, offer_cycle=Discount_2
current received: 336.0, prev received: 168.0, completed: 354.0

,time,event,amount,offer_id,offer_type,difficulty,duration
94332,168,offer received,NaN,discount_20_5_10,discount,20.0,10.0
94333,174,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
94334,264,transaction,17.63,NaN,NaN,NaN,NaN
94335,336,offer received,NaN,discount_20_5_10,discount,20.0,10.0
94336,348,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
94337,354,transaction,15.24,NaN,NaN,NaN,NaN
94338,354,offer completed,NaN,discount_20_5_10,discount,20.0,10.0

### person=5271c540bcec404eace3f82088f3a197, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 504.0, prev received: 336.0, completed: 546.0

,time,event,amount,offer_id,offer_type,difficulty,duration
98708,336,offer received,NaN,discount_10_2_10,discount,10.0,10.0
98709,366,transaction,1.25,NaN,NaN,NaN,NaN
98710,384,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
98711,396,transaction,1.13,NaN,NaN,NaN,NaN
98712,432,transaction,3.36,NaN,NaN,NaN,NaN
98713,486,transaction,0.25,NaN,NaN,NaN,NaN
98714,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
98715,510,transaction,2.24,NaN,NaN,NaN,NaN
98716,546,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
98717,546,transaction,4.06,NaN,NaN,NaN,NaN
98718,546,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=5b5449454f7842e3b0e8993012278079, offer_id=discount_7_3_7, offer_cycle=Discount_2
current received: 408.0, prev received: 336.0, completed: 504.0

,time,event,amount,offer_id,offer_type,difficulty,duration
108976,336,offer received,NaN,discount_7_3_7,discount,7.0,7.0
108977,390,transaction,2.27,NaN,NaN,NaN,NaN
108978,402,transaction,0.21,NaN,NaN,NaN,NaN
108979,408,offer received,NaN,discount_7_3_7,discount,7.0,7.0
108980,456,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
108981,468,transaction,0.53,NaN,NaN,NaN,NaN
108982,498,transaction,3.34,NaN,NaN,NaN,NaN
108983,504,offer received,NaN,discount_10_2_7,discount,10.0,7.0
108984,504,transaction,2.46,NaN,NaN,NaN,NaN
108985,504,offer completed,NaN,discount_7_3_7,discount,7.0,7.0

### person=5d37023bf1e84b39953a2d6ec2670708, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 504.0, prev received: 408.0, completed: 576.0

,time,event,amount,offer_id,offer_type,difficulty,duration
111503,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
111504,414,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
111505,438,transaction,0.97,NaN,NaN,NaN,NaN
111506,444,transaction,0.70,NaN,NaN,NaN,NaN
111507,486,transaction,0.97,NaN,NaN,NaN,NaN
111508,498,transaction,2.50,NaN,NaN,NaN,NaN
111509,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
111510,522,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
111511,528,transaction,3.83,NaN,NaN,NaN,NaN
111512,576,transaction,1.78,NaN,NaN,NaN,NaN
111513,576,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=5db55c030129497396446c4d07e15380, offer_id=discount_10_2_10, offer_cycle=Discount_3
current received: 504.0, prev received: 408.0, completed: 576.0

,time,event,amount,offer_id,offer_type,difficulty,duration
112049,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
112050,414,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
112051,438,transaction,2.40,NaN,NaN,NaN,NaN
112052,492,transaction,4.11,NaN,NaN,NaN,NaN
112053,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
112054,504,transaction,1.15,NaN,NaN,NaN,NaN
112055,522,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
112056,522,transaction,1.12,NaN,NaN,NaN,NaN
112057,576,transaction,6.50,NaN,NaN,NaN,NaN
112058,576,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=659c2598aaf34b2ab23852a2796e5a12, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 504.0, prev received: 408.0, completed: 630.0

,time,event,amount,offer_id,offer_type,difficulty,duration
121074,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
121075,414,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
121076,414,transaction,4.96,NaN,NaN,NaN,NaN
121077,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
121078,528,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
121079,528,transaction,0.57,NaN,NaN,NaN,NaN
121080,540,transaction,1.22,NaN,NaN,NaN,NaN
121081,576,offer received,NaN,bogo_5_5_7,bogo,5.0,7.0
121082,612,transaction,2.73,NaN,NaN,NaN,NaN
121083,630,offer viewed,NaN,bogo_5_5_7,bogo,5.0,7.0
121084,630,transaction,2.83,NaN,NaN,NaN,NaN
121085,630,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=65e5f48999544aedada20102086918f7, offer_id=discount_10_2_10, offer_cycle=Discount_3
current received: 576.0, prev received: 408.0, completed: 636.0

,time,event,amount,offer_id,offer_type,difficulty,duration
121403,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
121404,444,transaction,1.10,NaN,NaN,NaN,NaN
121405,486,transaction,8.50,NaN,NaN,NaN,NaN
121406,498,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
121407,504,offer received,NaN,informational_0_0_4,informational,0.0,4.0
121408,540,offer viewed,NaN,informational_0_0_4,informational,0.0,4.0
121409,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
121410,630,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
121411,636,transaction,1.12,NaN,NaN,NaN,NaN
121412,636,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=69ccf389b1674da9a9b2cfdf685de4be, offer_id=discount_10_2_7, offer_cycle=Discount_2
current received: 504.0, prev received: 408.0, completed: 576.0

,time,event,amount,offer_id,offer_type,difficulty,duration
126389,408,offer received,NaN,discount_10_2_7,discount,10.0,7.0
126390,426,transaction,1.81,NaN,NaN,NaN,NaN
126391,504,offer received,NaN,discount_10_2_7,discount,10.0,7.0
126392,528,offer viewed,NaN,discount_10_2_7,discount,10.0,7.0
126393,576,transaction,8.80,NaN,NaN,NaN,NaN
126394,576,offer completed,NaN,discount_10_2_7,discount,10.0,7.0

### person=6bb901d063a64c779320265b2aaeaee9, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 576.0, prev received: 504.0, completed: 612.0

,time,event,amount,offer_id,offer_type,difficulty,duration
128558,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
128559,504,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
128560,516,transaction,2.95,NaN,NaN,NaN,NaN
128561,522,transaction,1.25,NaN,NaN,NaN,NaN
128562,564,transaction,4.44,NaN,NaN,NaN,NaN
128563,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
128564,600,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
128565,612,transaction,6.24,NaN,NaN,NaN,NaN
128566,612,offer completed,NaN,discount_20_5_10,discount,20.0,10.0
128567,612,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=6d93d0f88895420d8dfdca9ff5390bce, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 576.0, prev received: 504.0, completed: 642.0

,time,event,amount,offer_id,offer_type,difficulty,duration
130847,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
130848,540,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
130849,540,transaction,3.09,NaN,NaN,NaN,NaN
130850,552,transaction,2.39,NaN,NaN,NaN,NaN
130851,558,transaction,0.98,NaN,NaN,NaN,NaN
130852,564,transaction,2.40,NaN,NaN,NaN,NaN
130853,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
130854,576,transaction,0.89,NaN,NaN,NaN,NaN
130855,624,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
130856,642,transaction,2.24,NaN,NaN,NaN,NaN
130857,642,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=6de6f7e081af455886287068f1b40419, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 576.0, prev received: 504.0, completed: 594.0

,time,event,amount,offer_id,offer_type,difficulty,duration
131226,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
131227,522,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
131228,534,transaction,3.94,NaN,NaN,NaN,NaN
131229,570,transaction,2.57,NaN,NaN,NaN,NaN
131230,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
131231,582,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
131232,594,transaction,6.42,NaN,NaN,NaN,NaN
131233,594,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=7065e5bd01f54bdd9ac511586276b4f7, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 576.0, prev received: 408.0, completed: 630.0

,time,event,amount,offer_id,offer_type,difficulty,duration
134004,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
134005,438,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
134006,516,transaction,9.00,NaN,NaN,NaN,NaN
134007,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
134008,612,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
134009,630,transaction,4.07,NaN,NaN,NaN,NaN
134010,630,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=774d6223fea8418a92c5742a4f55b7a9, offer_id=discount_20_5_10, offer_cycle=Discount_2
current received: 504.0, prev received: 336.0, completed: 546.0

,time,event,amount,offer_id,offer_type,difficulty,duration
142230,336,offer received,NaN,discount_20_5_10,discount,20.0,10.0
142231,342,transaction,12.36,NaN,NaN,NaN,NaN
142232,504,offer received,NaN,discount_20_5_10,discount,20.0,10.0
142233,546,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
142234,546,transaction,16.34,NaN,NaN,NaN,NaN
142235,546,offer completed,NaN,discount_20_5_10,discount,20.0,10.0

### person=7a4f2c4d9ddd4279a83ad86b4b5a81f2, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 576.0, prev received: 408.0, completed: 576.0

,time,event,amount,offer_id,offer_type,difficulty,duration
145666,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
145667,408,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
145668,414,transaction,1.11,NaN,NaN,NaN,NaN
145669,420,transaction,5.90,NaN,NaN,NaN,NaN
145670,444,transaction,1.75,NaN,NaN,NaN,NaN
145671,504,offer received,NaN,informational_0_0_3,informational,0.0,3.0
145672,534,offer viewed,NaN,informational_0_0_3,informational,0.0,3.0
145673,564,transaction,1.04,NaN,NaN,NaN,NaN
145674,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
145675,576,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
145676,576,transaction,2.06,NaN,NaN,NaN,NaN
145677,576,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=7cd76249602d4423b9f7a30d26bb0637, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 168.0, prev received: 0.0, completed: 240.0

,time,event,amount,offer_id,offer_type,difficulty,duration
149012,0,offer received,NaN,discount_10_2_10,discount,10.0,10.0
149013,6,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
149014,48,transaction,1.48,NaN,NaN,NaN,NaN
149015,126,transaction,4.63,NaN,NaN,NaN,NaN
149016,168,offer received,NaN,discount_10_2_10,discount,10.0,10.0
149017,168,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
149018,240,transaction,5.98,NaN,NaN,NaN,NaN
149019,240,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=7cd76249602d4423b9f7a30d26bb0637, offer_id=discount_10_2_10, offer_cycle=Discount_3
current received: 336.0, prev received: 168.0, completed: 336.0

,time,event,amount,offer_id,offer_type,difficulty,duration
149016,168,offer received,NaN,discount_10_2_10,discount,10.0,10.0
149017,168,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
149018,240,transaction,5.98,NaN,NaN,NaN,NaN
149019,240,offer completed,NaN,discount_10_2_10,discount,10.0,10.0
149020,258,transaction,0.42,NaN,NaN,NaN,NaN
149021,294,transaction,1.17,NaN,NaN,NaN,NaN
149022,300,transaction,0.05,NaN,NaN,NaN,NaN
149023,336,offer received,NaN,discount_10_2_10,discount,10.0,10.0
149024,336,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
149025,336,transaction,7.28,NaN,NaN,NaN,NaN
149026,336,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=84730da684cd4f548aee95ea4674bd17, offer_id=discount_7_3_7, offer_cycle=Discount_2
current received: 504.0, prev received: 408.0, completed: 570.0

,time,event,amount,offer_id,offer_type,difficulty,duration
158328,408,offer received,NaN,discount_7_3_7,discount,7.0,7.0
158329,408,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
158330,414,transaction,1.44,NaN,NaN,NaN,NaN
158331,432,transaction,4.27,NaN,NaN,NaN,NaN
158332,504,offer received,NaN,discount_7_3_7,discount,7.0,7.0
158333,540,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
158334,570,transaction,2.84,NaN,NaN,NaN,NaN
158335,570,offer completed,NaN,discount_7_3_7,discount,7.0,7.0

### person=86d1c0779345461fb1f5811627c93b3e, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 576.0, prev received: 504.0, completed: 588.0

,time,event,amount,offer_id,offer_type,difficulty,duration
161289,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
161290,516,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
161291,522,transaction,0.93,NaN,NaN,NaN,NaN
161292,552,transaction,1.27,NaN,NaN,NaN,NaN
161293,558,transaction,5.79,NaN,NaN,NaN,NaN
161294,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
161295,582,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
161296,588,transaction,2.21,NaN,NaN,NaN,NaN
161297,588,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=9045d97579294e3287696d71cad9c68d, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 576.0, prev received: 408.0, completed: 606.0

,time,event,amount,offer_id,offer_type,difficulty,duration
172854,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
172855,408,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
172856,462,transaction,2.31,NaN,NaN,NaN,NaN
172857,492,transaction,3.13,NaN,NaN,NaN,NaN
172858,504,offer received,NaN,discount_7_3_7,discount,7.0,7.0
172859,510,transaction,4.28,NaN,NaN,NaN,NaN
172860,564,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
172861,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
172862,606,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
172863,606,transaction,6.22,NaN,NaN,NaN,NaN
172864,606,offer completed,NaN,discount_10_2_10,discount,10.0,10.0
172865,606,offer completed,NaN,discount_7_3_7,discount,7.0,7.0

### person=91e8ec094d0a4e1ba88bf1b346c62762, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 504.0, prev received: 336.0, completed: 516.0

,time,event,amount,offer_id,offer_type,difficulty,duration
174971,336,offer received,NaN,discount_10_2_10,discount,10.0,10.0
174972,378,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
174973,402,transaction,6.24,NaN,NaN,NaN,NaN
174974,408,offer received,NaN,bogo_5_5_7,bogo,5.0,7.0
174975,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
174976,516,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
174977,516,transaction,6.45,NaN,NaN,NaN,NaN
174978,516,offer completed,NaN,discount_10_2_10,discount,10.0,10.0
174979,516,offer completed,NaN,bogo_5_5_7,bogo,5.0,7.0

### person=95f37a4a6f8b4bf6b9f91d62db4457dc, offer_id=discount_7_3_7, offer_cycle=Discount_2
current received: 504.0, prev received: 408.0, completed: 522.0

,time,event,amount,offer_id,offer_type,difficulty,duration
179815,408,offer received,NaN,discount_7_3_7,discount,7.0,7.0
179816,408,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
179817,414,transaction,1.77,NaN,NaN,NaN,NaN
179818,450,transaction,2.31,NaN,NaN,NaN,NaN
179819,480,transaction,2.56,NaN,NaN,NaN,NaN
179820,504,offer received,NaN,discount_7_3_7,discount,7.0,7.0
179821,510,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
179822,522,transaction,0.80,NaN,NaN,NaN,NaN
179823,522,offer completed,NaN,discount_7_3_7,discount,7.0,7.0

### person=9a9a6f44405f49fdb0c3fa45109767d5, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 408.0, prev received: 336.0, completed: 498.0

,time,event,amount,offer_id,offer_type,difficulty,duration
185414,336,offer received,NaN,discount_10_2_10,discount,10.0,10.0
185415,366,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
185416,402,transaction,3.69,NaN,NaN,NaN,NaN
185417,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
185418,432,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
185419,450,transaction,3.86,NaN,NaN,NaN,NaN
185420,480,transaction,0.91,NaN,NaN,NaN,NaN
185421,498,transaction,3.88,NaN,NaN,NaN,NaN
185422,498,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=9cbf831239914565aebb4495c0abecf8, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 576.0, prev received: 408.0, completed: 594.0

,time,event,amount,offer_id,offer_type,difficulty,duration
188560,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
188561,420,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
188562,450,transaction,2.18,NaN,NaN,NaN,NaN
188563,504,transaction,2.41,NaN,NaN,NaN,NaN
188564,510,transaction,4.55,NaN,NaN,NaN,NaN
188565,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
188566,582,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
188567,594,transaction,0.98,NaN,NaN,NaN,NaN
188568,594,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=a464b4c6b4e84d499a7e3af6f3460694, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 504.0, prev received: 408.0, completed: 582.0

,time,event,amount,offer_id,offer_type,difficulty,duration
198107,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
198108,408,transaction,0.80,NaN,NaN,NaN,NaN
198109,444,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
198110,474,transaction,4.74,NaN,NaN,NaN,NaN
198111,498,transaction,3.25,NaN,NaN,NaN,NaN
198112,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
198113,504,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
198114,540,transaction,0.81,NaN,NaN,NaN,NaN
198115,582,transaction,4.75,NaN,NaN,NaN,NaN
198116,582,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=a6d2bc2a28094a07a5c273dc542cefdc, offer_id=discount_20_5_10, offer_cycle=Discount_2
current received: 576.0, prev received: 504.0, completed: 582.0

,time,event,amount,offer_id,offer_type,difficulty,duration
201067,504,offer received,NaN,discount_20_5_10,discount,20.0,10.0
201068,528,transaction,14.32,NaN,NaN,NaN,NaN
201069,540,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
201070,576,offer received,NaN,discount_20_5_10,discount,20.0,10.0
201071,576,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
201072,582,transaction,17.24,NaN,NaN,NaN,NaN
201073,582,offer completed,NaN,discount_20_5_10,discount,20.0,10.0

### person=a96861615a41443faaf14546c970a012, offer_id=discount_7_3_7, offer_cycle=Discount_2
current received: 408.0, prev received: 336.0, completed: 492.0

,time,event,amount,offer_id,offer_type,difficulty,duration
203980,336,offer received,NaN,discount_7_3_7,discount,7.0,7.0
203981,372,transaction,3.96,NaN,NaN,NaN,NaN
203982,390,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
203983,408,offer received,NaN,discount_7_3_7,discount,7.0,7.0
203984,408,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
203985,474,transaction,3.01,NaN,NaN,NaN,NaN
203986,492,transaction,3.74,NaN,NaN,NaN,NaN
203987,492,offer completed,NaN,discount_7_3_7,discount,7.0,7.0

### person=ac0ba442fade4e9eb587feb5e408de99, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 576.0, prev received: 408.0, completed: 576.0

,time,event,amount,offer_id,offer_type,difficulty,duration
207253,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
207254,408,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
207255,438,transaction,1.05,NaN,NaN,NaN,NaN
207256,456,transaction,3.14,NaN,NaN,NaN,NaN
207257,504,offer received,NaN,informational_0_0_3,informational,0.0,3.0
207258,504,offer viewed,NaN,informational_0_0_3,informational,0.0,3.0
207259,540,transaction,0.13,NaN,NaN,NaN,NaN
207260,564,transaction,2.62,NaN,NaN,NaN,NaN
207261,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
207262,576,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
207263,576,transaction,3.17,NaN,NaN,NaN,NaN
207264,576,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=b4869c96c07e4be3aa9f2fc6027fe098, offer_id=discount_7_3_7, offer_cycle=Discount_2
current received: 504.0, prev received: 408.0, completed: 546.0

,time,event,amount,offer_id,offer_type,difficulty,duration
217289,408,offer received,NaN,discount_7_3_7,discount,7.0,7.0
217290,408,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
217291,474,transaction,1.43,NaN,NaN,NaN,NaN
217292,504,offer received,NaN,discount_7_3_7,discount,7.0,7.0
217293,504,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
217294,510,transaction,4.33,NaN,NaN,NaN,NaN
217295,546,transaction,1.68,NaN,NaN,NaN,NaN
217296,546,offer completed,NaN,discount_7_3_7,discount,7.0,7.0

### person=b4e0faec308c46c196235fdc0b0821f8, offer_id=discount_7_3_7, offer_cycle=Discount_2
current received: 576.0, prev received: 504.0, completed: 594.0

,time,event,amount,offer_id,offer_type,difficulty,duration
217680,504,offer received,NaN,discount_7_3_7,discount,7.0,7.0
217681,570,transaction,4.28,NaN,NaN,NaN,NaN
217682,576,offer received,NaN,discount_7_3_7,discount,7.0,7.0
217683,582,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
217684,582,transaction,1.59,NaN,NaN,NaN,NaN
217685,594,transaction,1.49,NaN,NaN,NaN,NaN
217686,594,offer completed,NaN,discount_7_3_7,discount,7.0,7.0

### person=b94c7601b17b41609daa2e3e56c3f53d, offer_id=discount_10_2_7, offer_cycle=Discount_2
current received: 576.0, prev received: 504.0, completed: 600.0

,time,event,amount,offer_id,offer_type,difficulty,duration
223241,504,offer received,NaN,discount_10_2_7,discount,10.0,7.0
223242,510,offer viewed,NaN,discount_10_2_7,discount,10.0,7.0
223243,510,transaction,0.78,NaN,NaN,NaN,NaN
223244,576,offer received,NaN,discount_10_2_7,discount,10.0,7.0
223245,576,offer viewed,NaN,discount_10_2_7,discount,10.0,7.0
223246,582,transaction,2.71,NaN,NaN,NaN,NaN
223247,600,transaction,6.55,NaN,NaN,NaN,NaN
223248,600,offer completed,NaN,discount_10_2_7,discount,10.0,7.0

### person=bc3694dd6a25450ca80f4d4a60719236, offer_id=discount_7_3_7, offer_cycle=Discount_2
current received: 576.0, prev received: 504.0, completed: 618.0

,time,event,amount,offer_id,offer_type,difficulty,duration
226669,504,offer received,NaN,discount_7_3_7,discount,7.0,7.0
226670,510,transaction,5.53,NaN,NaN,NaN,NaN
226671,516,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
226672,540,transaction,0.51,NaN,NaN,NaN,NaN
226673,546,transaction,0.31,NaN,NaN,NaN,NaN
226674,552,transaction,0.62,NaN,NaN,NaN,NaN
226675,576,offer received,NaN,discount_7_3_7,discount,7.0,7.0
226676,576,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
226677,618,transaction,1.58,NaN,NaN,NaN,NaN
226678,618,offer completed,NaN,discount_7_3_7,discount,7.0,7.0

### person=c99a06c81f8540b49cb6a66719ea62dc, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 576.0, prev received: 504.0, completed: 624.0

,time,event,amount,offer_id,offer_type,difficulty,duration
241691,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
241692,504,transaction,4.91,NaN,NaN,NaN,NaN
241693,522,transaction,0.37,NaN,NaN,NaN,NaN
241694,540,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
241695,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
241696,576,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
241697,588,transaction,2.47,NaN,NaN,NaN,NaN
241698,600,transaction,1.69,NaN,NaN,NaN,NaN
241699,624,transaction,4.53,NaN,NaN,NaN,NaN
241700,624,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=ca2f4be3edf7431aaf65060da4a9630b, offer_id=discount_20_5_10, offer_cycle=Discount_2
current received: 336.0, prev received: 168.0, completed: 408.0

,time,event,amount,offer_id,offer_type,difficulty,duration
242389,168,offer received,NaN,discount_20_5_10,discount,20.0,10.0
242390,174,transaction,0.95,NaN,NaN,NaN,NaN
242391,186,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
242392,240,transaction,0.95,NaN,NaN,NaN,NaN
242393,252,transaction,2.98,NaN,NaN,NaN,NaN
242394,270,transaction,1.25,NaN,NaN,NaN,NaN
242395,318,transaction,4.66,NaN,NaN,NaN,NaN
242396,330,transaction,1.13,NaN,NaN,NaN,NaN
242397,336,offer received,NaN,discount_20_5_10,discount,20.0,10.0
242398,342,transaction,1.63,NaN,NaN,NaN,NaN
242399,348,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
242400,384,transaction,3.69,NaN,NaN,NaN,NaN
242401,408,offer received,NaN,informational_0_0_3,informational,0.0,3.0
242402,408,transaction,5.55,NaN,NaN,NaN,NaN
242403,408,offer completed,NaN,discount_20_5_10,discount,20.0,10.0

### person=cae9515311754366aacb3044f0971484, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 576.0, prev received: 504.0, completed: 660.0

,time,event,amount,offer_id,offer_type,difficulty,duration
243143,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
243144,546,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
243145,552,transaction,1.10,NaN,NaN,NaN,NaN
243146,570,transaction,1.30,NaN,NaN,NaN,NaN
243147,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
243148,582,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
243149,594,transaction,3.53,NaN,NaN,NaN,NaN
243150,654,transaction,2.27,NaN,NaN,NaN,NaN
243151,660,transaction,1.82,NaN,NaN,NaN,NaN
243152,660,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=cca456a2b8f74306827a1e43dfc7b9ee, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 504.0, prev received: 408.0, completed: 576.0

,time,event,amount,offer_id,offer_type,difficulty,duration
245263,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
245264,414,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
245265,414,transaction,2.91,NaN,NaN,NaN,NaN
245266,444,transaction,1.93,NaN,NaN,NaN,NaN
245267,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
245268,504,transaction,0.94,NaN,NaN,NaN,NaN
245269,510,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
245270,540,transaction,2.89,NaN,NaN,NaN,NaN
245271,576,offer received,NaN,informational_0_0_3,informational,0.0,3.0
245272,576,transaction,2.55,NaN,NaN,NaN,NaN
245273,576,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=d030bccce03a4901a889b54f5930d938, offer_id=discount_20_5_10, offer_cycle=Discount_3
current received: 408.0, prev received: 336.0, completed: 486.0

,time,event,amount,offer_id,offer_type,difficulty,duration
249510,336,offer received,NaN,discount_20_5_10,discount,20.0,10.0
249511,336,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
249512,348,transaction,9.01,NaN,NaN,NaN,NaN
249513,384,transaction,8.84,NaN,NaN,NaN,NaN
249514,408,offer received,NaN,discount_20_5_10,discount,20.0,10.0
249515,450,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
249516,486,transaction,15.29,NaN,NaN,NaN,NaN
249517,486,offer completed,NaN,discount_20_5_10,discount,20.0,10.0

### person=d0e8e341348846b2af7879dedf4e3ff0, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 576.0, prev received: 504.0, completed: 600.0

,time,event,amount,offer_id,offer_type,difficulty,duration
250575,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
250576,540,transaction,5.88,NaN,NaN,NaN,NaN
250577,546,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
250578,546,transaction,1.49,NaN,NaN,NaN,NaN
250579,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
250580,582,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
250581,600,transaction,3.49,NaN,NaN,NaN,NaN
250582,600,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=d660d99086664c348480011c5c013529, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 336.0, prev received: 168.0, completed: 336.0

,time,event,amount,offer_id,offer_type,difficulty,duration
256952,168,offer received,NaN,discount_10_2_10,discount,10.0,10.0
256953,192,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
256954,324,transaction,7.10,NaN,NaN,NaN,NaN
256955,336,offer received,NaN,discount_10_2_10,discount,10.0,10.0
256956,336,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
256957,336,transaction,7.87,NaN,NaN,NaN,NaN
256958,336,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=d9d1c595b0ce4da695e96312369e5c4c, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 408.0, prev received: 336.0, completed: 522.0

,time,event,amount,offer_id,offer_type,difficulty,duration
260849,336,offer received,NaN,discount_10_2_10,discount,10.0,10.0
260850,336,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
260851,342,transaction,4.37,NaN,NaN,NaN,NaN
260852,378,transaction,0.94,NaN,NaN,NaN,NaN
260853,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
260854,414,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
260855,414,transaction,2.47,NaN,NaN,NaN,NaN
260856,504,offer received,NaN,bogo_5_5_5,bogo,5.0,5.0
260857,510,offer viewed,NaN,bogo_5_5_5,bogo,5.0,5.0
260858,522,transaction,2.51,NaN,NaN,NaN,NaN
260859,522,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=dc4fde598436441ca540a5d79fbdbaac, offer_id=discount_20_5_10, offer_cycle=Discount_2
current received: 336.0, prev received: 168.0, completed: 360.0

,time,event,amount,offer_id,offer_type,difficulty,duration
263943,168,offer received,NaN,discount_20_5_10,discount,20.0,10.0
263944,216,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
263945,294,transaction,19.02,NaN,NaN,NaN,NaN
263946,336,offer received,NaN,discount_20_5_10,discount,20.0,10.0
263947,348,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
263948,360,transaction,14.55,NaN,NaN,NaN,NaN
263949,360,offer completed,NaN,discount_20_5_10,discount,20.0,10.0

### person=e3325dbf54de4e3f805d856ec918b757, offer_id=discount_10_2_10, offer_cycle=Discount_2
current received: 168.0, prev received: 0.0, completed: 210.0

,time,event,amount,offer_id,offer_type,difficulty,duration
272655,0,offer received,NaN,discount_10_2_10,discount,10.0,10.0
272656,0,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
272657,84,transaction,5.87,NaN,NaN,NaN,NaN
272658,168,offer received,NaN,discount_10_2_10,discount,10.0,10.0
272659,168,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
272660,210,transaction,6.64,NaN,NaN,NaN,NaN
272661,210,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=e898f8d0cc514692aee817765d1584e9, offer_id=discount_10_2_10, offer_cycle=Discount_3
current received: 576.0, prev received: 504.0, completed: 642.0

,time,event,amount,offer_id,offer_type,difficulty,duration
279178,504,offer received,NaN,discount_10_2_10,discount,10.0,10.0
279179,510,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
279180,528,transaction,2.23,NaN,NaN,NaN,NaN
279181,534,transaction,7.73,NaN,NaN,NaN,NaN
279182,576,offer received,NaN,discount_10_2_10,discount,10.0,10.0
279183,576,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
279184,642,transaction,1.63,NaN,NaN,NaN,NaN
279185,642,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=edc7b04392144da9979f3077095f268a, offer_id=discount_10_2_10, offer_cycle=Discount_3
current received: 408.0, prev received: 336.0, completed: 474.0

,time,event,amount,offer_id,offer_type,difficulty,duration
284956,336,offer received,NaN,discount_10_2_10,discount,10.0,10.0
284957,372,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
284958,384,transaction,5.85,NaN,NaN,NaN,NaN
284959,396,transaction,1.41,NaN,NaN,NaN,NaN
284960,408,offer received,NaN,discount_10_2_10,discount,10.0,10.0
284961,432,transaction,0.39,NaN,NaN,NaN,NaN
284962,462,offer viewed,NaN,discount_10_2_10,discount,10.0,10.0
284963,474,transaction,7.43,NaN,NaN,NaN,NaN
284964,474,offer completed,NaN,discount_10_2_10,discount,10.0,10.0

### person=f3934f05d51f47c7a470661cbb774075, offer_id=discount_20_5_10, offer_cycle=Discount_2
current received: 408.0, prev received: 336.0, completed: 456.0

,time,event,amount,offer_id,offer_type,difficulty,duration
291680,336,offer received,NaN,discount_20_5_10,discount,20.0,10.0
291681,402,transaction,6.55,NaN,NaN,NaN,NaN
291682,408,offer received,NaN,discount_20_5_10,discount,20.0,10.0
291683,426,transaction,8.57,NaN,NaN,NaN,NaN
291684,456,offer viewed,NaN,discount_20_5_10,discount,20.0,10.0
291685,456,transaction,7.26,NaN,NaN,NaN,NaN
291686,456,offer completed,NaN,discount_20_5_10,discount,20.0,10.0

### person=f4f6fa9f813640baab5fa4e66c3b6707, offer_id=discount_10_2_7, offer_cycle=Discount_2
current received: 408.0, prev received: 336.0, completed: 462.0

,time,event,amount,offer_id,offer_type,difficulty,duration
293492,336,offer received,NaN,discount_10_2_7,discount,10.0,7.0
293493,360,offer viewed,NaN,discount_10_2_7,discount,10.0,7.0
293494,390,transaction,3.60,NaN,NaN,NaN,NaN
293495,408,offer received,NaN,discount_10_2_7,discount,10.0,7.0
293496,426,transaction,0.74,NaN,NaN,NaN,NaN
293497,438,offer viewed,NaN,discount_10_2_7,discount,10.0,7.0
293498,444,transaction,3.51,NaN,NaN,NaN,NaN
293499,462,transaction,2.17,NaN,NaN,NaN,NaN
293500,462,offer completed,NaN,discount_10_2_7,discount,10.0,7.0

### person=f8961e32857d4f2f97183ef480da2ab9, offer_id=discount_7_3_7, offer_cycle=Discount_2
current received: 408.0, prev received: 336.0, completed: 408.0

,time,event,amount,offer_id,offer_type,difficulty,duration
297580,336,offer received,NaN,discount_7_3_7,discount,7.0,7.0
297581,360,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
297582,402,transaction,2.44,NaN,NaN,NaN,NaN
297583,408,offer received,NaN,discount_7_3_7,discount,7.0,7.0
297584,408,offer viewed,NaN,discount_7_3_7,discount,7.0,7.0
297585,408,transaction,5.08,NaN,NaN,NaN,NaN
297586,408,offer completed,NaN,discount_7_3_7,discount,7.0,7.0

### 정상흐름 amount 구해보기

In [59]:
normal_total_before = promotion_final.loc[
    promotion_final['is_deduplicated'].eq(1),
    'amount_raw'
].sum()

normal_total_after = promotion_final.loc[
    promotion_final['is_deduplicated'].eq(1),
    'amount'
].sum()

print('수정 전 정상흐름 amount 합:', normal_total_before)
print('수정 후 정상흐름 amount 합:', normal_total_after)
print('두 amount 차이:', round(normal_total_after - normal_total_before, 2))

수정 전 정상흐름 amount 합: 442993.24
수정 후 정상흐름 amount 합: 486645.59
두 amount 차이: 43652.35

# `amount` 재계산 및 보정 정리

이 노트북에서는 `promotion_df.csv`를 기준으로 offer row의 `amount`를 다시 계산했다.

## 작업 내용
- `offer received`부터 `offer completed`까지의 transaction 금액을 다시 합쳐 `completion_amount_current`를 계산했다.
- 현재 received 기준 금액이 `difficulty`를 못 넘는 정상 흐름 행만 따로 뽑았다.
- 그 행들에 한해서만 이전 `received`를 시작점으로 다시 계산한 `completion_amount_prev_received`를 확인했다.
- `current`가 부족할 때만 `prev_received`를 보정값으로 사용했다.
- `offer viewed` 이후의 프로모션 영향액도 `promo_influenced_amount`와 `promo_influenced_amount_prev_received`로 함께 계산했다.
- 최종적으로 `adjusted_completion_amount`를 만들고, `amount_raw`는 원본값으로 보존했다.
- 저장용 최종 파일은 `promotion_final.csv`로 만들었다.

## 핵심 정리
- `completion_amount_current` = 현재 received 기준 총 결제액
- `completion_amount_prev_received` = 이전 received 기준 총 결제액
- `promo_influenced_amount` = viewed 이후 결제액
- `promo_influenced_amount_prev_received` = 이전 received 기준 viewed 이후 결제액
- `adjusted_completion_amount` = 최종 보정된 amount

## 해석
- `current`가 충분하면 그대로 사용했다.
- `current`가 부족한 행만 `prev_received`로 보정했다.
- 정상 흐름의 offer row를 더 정확하게 해석할 수 있도록 amount를 다시 정리한 작업이다.