# event 컬럼 체크하는 파일입니다!

In [1]:
import pandas as pd
import warnings
import numpy as np
import ast

import matplotlib.pyplot as plt
import seaborn as sns

# 출력 설정
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None) # 모든 컬럼이 다 보인다.
pd.set_option('display.max_rows', 100) # 행 출력 개수 제한

# 한글 폰트 설정
import platform
if platform.system() == 'Windows':
    plt.rcParams['font.family'] = 'Malgun Gothic'
elif platform.system() == 'Darwin':  # macOS
    plt.rcParams['font.family'] = 'AppleGothic'
else:  # Linux
    plt.rcParams['font.family'] = 'NanumGothic'

plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['figure.figsize'] = (12, 6)

# 컬럼 너비 제한을 해제
pd.set_option('display.max_colwidth', None)
# 컬럼 너비 설정 초기화
# pd.reset_option('display.max_colwidth')

print("="*60)
print("라이브러리 로드 완료!")
print("한글 폰트 설정 완료!")
print("="*60)

============================================================
라이브러리 로드 완료!
한글 폰트 설정 완료!
============================================================

In [2]:
portfolio = pd.read_csv('../data/portfolio.csv')
profile = pd.read_csv('../data/profile.csv') # (17000, 6)
transcript = pd.read_csv('../data/transcript.csv') # (306534, 8)

In [3]:
# value컬럼 뜯어보기

# 문자열 형태의 value 컬럼 -> 딕셔너리 형태로 변환
transcript['value'] = transcript['value'].apply(ast.literal_eval)

# 딕셔너리의 키 들을 새로운 컬럼으로 전개
value_df = pd.DataFrame(transcript['value'].tolist())
transcript = pd.concat([transcript, value_df], axis=1)

# offer id를 offer_id로 컬럼명 통일
transcript['offer_id'] = transcript['offer_id'].fillna(transcript['offer id'])
transcript = transcript.drop('offer id', axis=1)

In [4]:
display(transcript.head())
display(transcript.tail())

,Unnamed: 0,person,event,value,time,amount,offer_id,reward
0,0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0,NaN,9b98b8c7a33c4b65b9aebfe6a799e6d9,NaN
1,1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0,NaN,0b1e1539f2cc45b7b9fa7c272da2e1d7,NaN
2,2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0,NaN,2906b810c7d4411798c6938adc9daaa5,NaN
3,3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0,NaN,fafdcd668e3743c1bb461111dcafc2a4,NaN
4,4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,NaN

,Unnamed: 0,person,event,value,time,amount,offer_id,reward
306529,306529,b3a1272bc9904337b331bf348c3e8c17,transaction,{'amount': 1.5899999999999999},714,1.59,NaN,NaN
306530,306530,68213b08d99a4ae1b0dcb72aebd9aa35,transaction,{'amount': 9.53},714,9.53,NaN,NaN
306531,306531,a00058cf10334a308c68e7631c529907,transaction,{'amount': 3.61},714,3.61,NaN,NaN
306532,306532,76ddbd6576844afe811f1a3c0fbb5bec,transaction,{'amount': 3.5300000000000002},714,3.53,NaN,NaN
306533,306533,c02b10e8752c4d8e9b73f918558531f7,transaction,{'amount': 4.05},714,4.05,NaN,NaN

In [5]:
portfolio

,Unnamed: 0,reward,channels,difficulty,duration,offer_type,id
0,0,10,"['email', 'mobile', 'social']",10,7,bogo,ae264e3637204a6fb9bb56bc8210ddfd
1,1,10,"['web', 'email', 'mobile', 'social']",10,5,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
2,2,0,"['web', 'email', 'mobile']",0,4,informational,3f207df678b143eea3cee63160fa8bed
3,3,5,"['web', 'email', 'mobile']",5,7,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
4,4,5,"['web', 'email']",20,10,discount,0b1e1539f2cc45b7b9fa7c272da2e1d7
5,5,3,"['web', 'email', 'mobile', 'social']",7,7,discount,2298d6c36e964ae4a3e7e9706d1fb8c2
6,6,2,"['web', 'email', 'mobile', 'social']",10,10,discount,fafdcd668e3743c1bb461111dcafc2a4
7,7,0,"['email', 'mobile', 'social']",0,3,informational,5a8bc65990b245e5a138643cd4eb9837
8,8,5,"['web', 'email', 'mobile', 'social']",5,5,bogo,f19421c1d4aa40978ebb69ca19b0e20d
9,9,2,"['web', 'email', 'mobile']",10,7,discount,2906b810c7d4411798c6938adc9daaa5

In [6]:
profile

,Unnamed: 0,gender,age,id,became_member_on,income
0,0,NaN,118,68be06ca386d4c31939f3a4f0e3dd783,20170212,NaN
1,1,F,55,0610b486422d4921ae7d2bf64640c50b,20170715,112000.0
2,2,NaN,118,38fe809add3b4fcf9315a9694bb96ff5,20180712,NaN
3,3,F,75,78afa995795e4d85b5d9ceeca43f5fef,20170509,100000.0
4,4,NaN,118,a03223e636434f42ac4c3df47e8bac43,20170804,NaN
...,...,...,...,...,...,...
16995,16995,F,45,6d5f3a774f3d4714ab0c092238f3a1d7,20180604,54000.0
16996,16996,M,61,2cb4f97358b841b9a9773a7aa05a9d77,20180713,72000.0
16997,16997,M,49,01d26f638c274aa0b965d24cefe3183f,20170126,73000.0
16998,16998,F,83,9dc1421481194dcd9400aec7c9ae6366,20160307,50000.0
16999,16999,F,62,e4052622e5ba45a8b96b59aba68cf068,20170722,82000.0

In [7]:
profile.shape

(17000, 6)

-transcript(person) -> (left) -> profile(id) ->

In [8]:
# 3가지 테이블 조인
df = pd.merge(transcript, profile, left_on='person', right_on='id', how='left')
df = pd.merge(df, portfolio, left_on='offer_id', right_on='id', how='left')
df

#Unnamed: 0_y, value, id_x, Unnamed: 0, id_y 제거.
#Unnamed: 0_x -> index, person -> customer_id, reward_y -> promotion_reward, channels -> promotion_channels, difficulty -> promotion_difficulty, duration -> promotion_duration, offer_type -> promotion_offer_type

,Unnamed: 0_x,person,event,value,time,amount,offer_id,reward_x,Unnamed: 0_y,gender,age,id_x,became_member_on,income,Unnamed: 0,reward_y,channels,difficulty,duration,offer_type,id_y
0,0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0,NaN,9b98b8c7a33c4b65b9aebfe6a799e6d9,NaN,3,F,75,78afa995795e4d85b5d9ceeca43f5fef,20170509,100000.0,3.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
1,1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0,NaN,0b1e1539f2cc45b7b9fa7c272da2e1d7,NaN,4,NaN,118,a03223e636434f42ac4c3df47e8bac43,20170804,NaN,4.0,5.0,"['web', 'email']",20.0,10.0,discount,0b1e1539f2cc45b7b9fa7c272da2e1d7
2,2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0,NaN,2906b810c7d4411798c6938adc9daaa5,NaN,5,M,68,e2127556f4f64592b11af22de27a7932,20180426,70000.0,9.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,2906b810c7d4411798c6938adc9daaa5
3,3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0,NaN,fafdcd668e3743c1bb461111dcafc2a4,NaN,6,NaN,118,8ec6ce2a7e7949b1bf142def7d0e0586,20170925,NaN,6.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,fafdcd668e3743c1bb461111dcafc2a4
4,4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,NaN,7,NaN,118,68617ca6246f4fbc85e91a2a49552598,20171002,NaN,1.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306529,306529,b3a1272bc9904337b331bf348c3e8c17,transaction,{'amount': 1.5899999999999999},714,1.59,NaN,NaN,16959,M,66,b3a1272bc9904337b331bf348c3e8c17,20180101,47000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306530,306530,68213b08d99a4ae1b0dcb72aebd9aa35,transaction,{'amount': 9.53},714,9.53,NaN,NaN,16964,M,52,68213b08d99a4ae1b0dcb72aebd9aa35,20180408,62000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306531,306531,a00058cf10334a308c68e7631c529907,transaction,{'amount': 3.61},714,3.61,NaN,NaN,16979,F,63,a00058cf10334a308c68e7631c529907,20130922,52000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306532,306532,76ddbd6576844afe811f1a3c0fbb5bec,transaction,{'amount': 3.5300000000000002},714,3.53,NaN,NaN,16987,M,57,76ddbd6576844afe811f1a3c0fbb5bec,20160709,40000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306533,306533,c02b10e8752c4d8e9b73f918558531f7,transaction,{'amount': 4.05},714,4.05,NaN,NaN,16994,NaN,118,c02b10e8752c4d8e9b73f918558531f7,20151211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Unnamed: 0_y, value, id_x, Unnamed: 0, id_y 제거.
cols_to_drop = ['Unnamed: 0_y', 'value', 'id_x', 'Unnamed: 0', 'id_y']
df = df.drop(columns=cols_to_drop, errors='ignore')

# 컬럼명 직관적으로 변경
cols_to_rename = {
    'Unnamed: 0_x': 'index',
    'person': 'person_id',
    'reward_y': 'promotion_reward',
    'channels': 'promotion_channels',
    'difficulty': 'promotion_difficulty',
    'duration': 'promotion_duration',
    'offer_type': 'promotion_offer_type',
    'reward_x': 'reward'
}
df = df.rename(columns=cols_to_rename)

## 본격 event 컬럼 뜯어보기

### 가설 1. offer completed는 무조건 transacion 뒤?

In [10]:
# person_id, time순으로 정렬
df_sorted = df.sort_values(by=['person_id', 'time']).copy()

df_sorted['prev_event'] = df_sorted.groupby('person_id')['event'].shift(1)
df_sorted['prev_time'] = df_sorted.groupby('person_id')['time'].shift(1)


completed_df = df_sorted[df_sorted['event'] == 'offer completed']
print(completed_df['prev_event'].value_counts(dropna=False))
# prev_event
# transaction        30617
# offer completed     2962
# offer completed는 transaction 바로 뒤 혹은, offer completed 바로 뒤
print(f"offer completed 바로 직전의 이벤트에 대한 전체 개수 : {completed_df['prev_event'].value_counts(dropna=False).sum()}")
print("="*80)

completed_df['time_diff'] = completed_df['time'] - completed_df['prev_time']
print(completed_df['time_diff'].value_counts(dropna=False).head())
# offer completed는 곧바로 행해진다는 것을 알 수 있다.

prev_event
transaction        30617
offer completed     2962
Name: count, dtype: int64
offer completed 바로 직전의 이벤트에 대한 전체 개수 : 33579
================================================================================
time_diff
0.0    33579
Name: count, dtype: int64

- offer completed는 transaction 뒤 또는 offer completed 뒤
- transaction 뒤라면 정상. offer completed 뒤라면 offer_id가 달라야 정상

In [11]:
df_sorted['next_event'] = df_sorted.groupby('person_id')['event'].shift(-1)

condition = (
    (df_sorted['event'] == 'offer completed') & 
    ((df_sorted['prev_event'] == 'offer completed') | (df_sorted['next_event'] == 'offer completed'))
)

multi_completed_df = df_sorted[condition]

print(f"단일 completed를 제외한, 연속 completed 이벤트 총 개수: {len(multi_completed_df)}건\n")

multi_completed_df

단일 completed를 제외한, 연속 completed 이벤트 총 개수: 5832건

,index,person_id,event,time,amount,offer_id,reward,gender,age,became_member_on,income,promotion_reward,promotion_channels,promotion_difficulty,promotion_duration,promotion_offer_type,prev_event,prev_time,next_event
258980,258980,0011e0d4e6b944f998e987f904e8c1e5,offer completed,576,NaN,0b1e1539f2cc45b7b9fa7c272da2e1d7,5.0,O,40,20180109,57000.0,5.0,"['web', 'email']",20.0,10.0,discount,transaction,576.0,offer completed
258981,258981,0011e0d4e6b944f998e987f904e8c1e5,offer completed,576,NaN,9b98b8c7a33c4b65b9aebfe6a799e6d9,5.0,O,40,20180109,57000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,offer completed,576.0,transaction
218936,218936,0020c2b971eb4e9188eac86d93036a77,offer completed,510,NaN,fafdcd668e3743c1bb461111dcafc2a4,2.0,F,59,20160304,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,transaction,510.0,offer completed
218937,218937,0020c2b971eb4e9188eac86d93036a77,offer completed,510,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,10.0,F,59,20160304,90000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,offer completed,510.0,transaction
281776,281776,00ae03011f9f49b8a4b3e6d416678b0b,offer completed,618,NaN,ae264e3637204a6fb9bb56bc8210ddfd,10.0,M,55,20151115,83000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,transaction,618.0,offer completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68854,68854,fff29fb549084123bd046dbc5ceb4faa,offer completed,168,NaN,fafdcd668e3743c1bb461111dcafc2a4,2.0,F,59,20170831,93000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,offer completed,168.0,transaction
176859,176859,fff29fb549084123bd046dbc5ceb4faa,offer completed,426,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,10.0,F,59,20170831,93000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,transaction,426.0,offer completed
176860,176860,fff29fb549084123bd046dbc5ceb4faa,offer completed,426,NaN,f19421c1d4aa40978ebb69ca19b0e20d,5.0,F,59,20170831,93000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,offer completed,426.0,offer viewed
269951,269951,fff7576017104bcc8677a8d63322b5e1,offer completed,594,NaN,fafdcd668e3743c1bb461111dcafc2a4,2.0,M,71,20171031,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,transaction,594.0,offer completed
269952,269952,fff7576017104bcc8677a8d63322b5e1,offer completed,594,NaN,9b98b8c7a33c4b65b9aebfe6a799e6d9,5.0,M,71,20171031,73000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,offer completed,594.0,transaction

In [12]:
same_offer_completed = multi_completed_df[
    multi_completed_df.duplicated(subset=['person_id', 'time', 'offer_id'], keep=False)
]

print(f"같은 시간에 같은 offer completed 가 들어간 총 건수: {len(same_offer_completed)}건\n")
same_offer_completed

같은 시간에 같은 offer completed 가 들어간 총 건수: 793건

,index,person_id,event,time,amount,offer_id,reward,gender,age,became_member_on,income,promotion_reward,promotion_channels,promotion_difficulty,promotion_duration,promotion_offer_type,prev_event,prev_time,next_event
218058,218058,00d7c95f793a4212af44e632fdc1e431,offer completed,504,NaN,2906b810c7d4411798c6938adc9daaa5,2.0,M,71,20161229,75000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,transaction,504.0,offer completed
218060,218060,00d7c95f793a4212af44e632fdc1e431,offer completed,504,NaN,2906b810c7d4411798c6938adc9daaa5,2.0,M,71,20161229,75000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,offer completed,504.0,transaction
220133,220133,01925607d99c460996c281f17cdbb9e2,offer completed,510,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,10.0,F,57,20151119,116000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,transaction,510.0,offer completed
220134,220134,01925607d99c460996c281f17cdbb9e2,offer completed,510,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,10.0,F,57,20151119,116000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,offer completed,510.0,offer received
171646,171646,01956670cf414b309675aa73368b94a9,offer completed,420,NaN,2906b810c7d4411798c6938adc9daaa5,2.0,M,52,20160825,95000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,transaction,420.0,offer completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274288,274288,ff6a080134fc44dc9c7e7b5abcfbe849,offer completed,600,NaN,ae264e3637204a6fb9bb56bc8210ddfd,10.0,M,73,20171207,115000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,offer completed,600.0,transaction
228665,228665,ff80a43ecb34439491bd9ae1cff7c5fc,offer completed,528,NaN,fafdcd668e3743c1bb461111dcafc2a4,2.0,M,54,20140204,57000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,transaction,528.0,offer completed
228666,228666,ff80a43ecb34439491bd9ae1cff7c5fc,offer completed,528,NaN,fafdcd668e3743c1bb461111dcafc2a4,2.0,M,54,20140204,57000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,offer completed,528.0,transaction
140993,140993,ff95e0a9cdfd4030958762dadcb11e1a,offer completed,372,NaN,0b1e1539f2cc45b7b9fa7c272da2e1d7,5.0,M,79,20170520,93000.0,5.0,"['web', 'email']",20.0,10.0,discount,transaction,372.0,offer completed
140994,140994,ff95e0a9cdfd4030958762dadcb11e1a,offer completed,372,NaN,0b1e1539f2cc45b7b9fa7c272da2e1d7,5.0,M,79,20170520,93000.0,5.0,"['web', 'email']",20.0,10.0,discount,offer completed,372.0,transaction

- 동일 시간에 동일한 offer_id의 offer completed가 여럿 있는것이 조금 이상하다고 생각함.
- person별로 뜯어볼까 싶다.

In [13]:
same_offer_completed['person_id'].nunique()

394

In [14]:
df[df['person_id']=='00d7c95f793a4212af44e632fdc1e431']

,index,person_id,event,time,amount,offer_id,reward,gender,age,became_member_on,income,promotion_reward,promotion_channels,promotion_difficulty,promotion_duration,promotion_offer_type
11580,11580,00d7c95f793a4212af44e632fdc1e431,offer received,0,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,NaN,M,71,20161229,75000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo
20121,20121,00d7c95f793a4212af44e632fdc1e431,offer viewed,12,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,NaN,M,71,20161229,75000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo
39436,39436,00d7c95f793a4212af44e632fdc1e431,transaction,84,29.39,NaN,NaN,M,71,20161229,75000.0,NaN,NaN,NaN,NaN,NaN
39437,39437,00d7c95f793a4212af44e632fdc1e431,offer completed,84,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,10.0,M,71,20161229,75000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo
90423,90423,00d7c95f793a4212af44e632fdc1e431,transaction,228,20.69,NaN,NaN,M,71,20161229,75000.0,NaN,NaN,NaN,NaN,NaN
122425,122425,00d7c95f793a4212af44e632fdc1e431,offer received,336,NaN,2906b810c7d4411798c6938adc9daaa5,NaN,M,71,20161229,75000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount
162253,162253,00d7c95f793a4212af44e632fdc1e431,offer received,408,NaN,9b98b8c7a33c4b65b9aebfe6a799e6d9,NaN,M,71,20161229,75000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo
201444,201444,00d7c95f793a4212af44e632fdc1e431,offer viewed,498,NaN,9b98b8c7a33c4b65b9aebfe6a799e6d9,NaN,M,71,20161229,75000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo
213173,213173,00d7c95f793a4212af44e632fdc1e431,offer received,504,NaN,2906b810c7d4411798c6938adc9daaa5,NaN,M,71,20161229,75000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount
218057,218057,00d7c95f793a4212af44e632fdc1e431,transaction,504,18.58,NaN,NaN,M,71,20161229,75000.0,NaN,NaN,NaN,NaN,NaN
218058,218058,00d7c95f793a4212af44e632fdc1e431,offer completed,504,NaN,2906b810c7d4411798c6938adc9daaa5,2.0,M,71,20161229,75000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount
218059,218059,00d7c95f793a4212af44e632fdc1e431,offer completed,504,NaN,9b98b8c7a33c4b65b9aebfe6a799e6d9,5.0,M,71,20161229,75000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo
218060,218060,00d7c95f793a4212af44e632fdc1e431,offer completed,504,NaN,2906b810c7d4411798c6938adc9daaa5,2.0,M,71,20161229,75000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount
232669,232669,00d7c95f793a4212af44e632fdc1e431,transaction,534,19.85,NaN,NaN,M,71,20161229,75000.0,NaN,NaN,NaN,NaN,NaN
237183,237183,00d7c95f793a4212af44e632fdc1e431,transaction,546,19.87,NaN,NaN,M,71,20161229,75000.0,NaN,NaN,NaN,NaN,NaN
241148,241148,00d7c95f793a4212af44e632fdc1e431,transaction,558,29.10,NaN,NaN,M,71,20161229,75000.0,NaN,NaN,NaN,NaN,NaN
256775,256775,00d7c95f793a4212af44e632fdc1e431,offer received,576,NaN,fafdcd668e3743c1bb461111dcafc2a4,NaN,M,71,20161229,75000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount
292979,292979,00d7c95f793a4212af44e632fdc1e431,offer viewed,654,NaN,fafdcd668e3743c1bb461111dcafc2a4,NaN,M,71,20161229,75000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount
296188,296188,00d7c95f793a4212af44e632fdc1e431,transaction,666,24.94,NaN,NaN,M,71,20161229,75000.0,NaN,NaN,NaN,NaN,NaN
296189,296189,00d7c95f793a4212af44e632fdc1e431,offer completed,666,NaN,fafdcd668e3743c1bb461111dcafc2a4,2.0,M,71,20161229,75000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount

In [15]:
df[df['person_id']=='01925607d99c460996c281f17cdbb9e2']

,index,person_id,event,time,amount,offer_id,reward,gender,age,became_member_on,income,promotion_reward,promotion_channels,promotion_difficulty,promotion_duration,promotion_offer_type
120720,120720,01925607d99c460996c281f17cdbb9e2,offer received,336,NaN,f19421c1d4aa40978ebb69ca19b0e20d,NaN,F,57,20151119,116000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo
125352,125352,01925607d99c460996c281f17cdbb9e2,offer viewed,336,NaN,f19421c1d4aa40978ebb69ca19b0e20d,NaN,F,57,20151119,116000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo
125353,125353,01925607d99c460996c281f17cdbb9e2,transaction,336,29.14,NaN,NaN,F,57,20151119,116000.0,NaN,NaN,NaN,NaN,NaN
125354,125354,01925607d99c460996c281f17cdbb9e2,offer completed,336,NaN,f19421c1d4aa40978ebb69ca19b0e20d,5.0,F,57,20151119,116000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo
160527,160527,01925607d99c460996c281f17cdbb9e2,offer received,408,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,NaN,F,57,20151119,116000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo
185999,185999,01925607d99c460996c281f17cdbb9e2,offer viewed,450,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,NaN,F,57,20151119,116000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo
207769,207769,01925607d99c460996c281f17cdbb9e2,offer received,504,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,NaN,F,57,20151119,116000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo
220132,220132,01925607d99c460996c281f17cdbb9e2,transaction,510,25.48,NaN,NaN,F,57,20151119,116000.0,NaN,NaN,NaN,NaN,NaN
220133,220133,01925607d99c460996c281f17cdbb9e2,offer completed,510,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,10.0,F,57,20151119,116000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo
220134,220134,01925607d99c460996c281f17cdbb9e2,offer completed,510,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,10.0,F,57,20151119,116000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo
255020,255020,01925607d99c460996c281f17cdbb9e2,offer received,576,NaN,ae264e3637204a6fb9bb56bc8210ddfd,NaN,F,57,20151119,116000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo

In [16]:
df[df['person_id']=='01956670cf414b309675aa73368b94a9']

,index,person_id,event,time,amount,offer_id,reward,gender,age,became_member_on,income,promotion_reward,promotion_channels,promotion_difficulty,promotion_duration,promotion_offer_type
1950,1950,01956670cf414b309675aa73368b94a9,offer received,0,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,NaN,M,52,20160825,95000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo
22640,22640,01956670cf414b309675aa73368b94a9,offer viewed,24,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,NaN,M,52,20160825,95000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo
35755,35755,01956670cf414b309675aa73368b94a9,transaction,72,23.62,NaN,NaN,M,52,20160825,95000.0,NaN,NaN,NaN,NaN,NaN
35756,35756,01956670cf414b309675aa73368b94a9,offer completed,72,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,10.0,M,52,20160825,95000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo
38420,38420,01956670cf414b309675aa73368b94a9,transaction,84,22.67,NaN,NaN,M,52,20160825,95000.0,NaN,NaN,NaN,NaN,NaN
42215,42215,01956670cf414b309675aa73368b94a9,transaction,102,23.09,NaN,NaN,M,52,20160825,95000.0,NaN,NaN,NaN,NaN,NaN
45629,45629,01956670cf414b309675aa73368b94a9,transaction,120,31.71,NaN,NaN,M,52,20160825,95000.0,NaN,NaN,NaN,NaN,NaN
55147,55147,01956670cf414b309675aa73368b94a9,offer received,168,NaN,2298d6c36e964ae4a3e7e9706d1fb8c2,NaN,M,52,20160825,95000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount
90761,90761,01956670cf414b309675aa73368b94a9,offer viewed,234,NaN,2298d6c36e964ae4a3e7e9706d1fb8c2,NaN,M,52,20160825,95000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount
101621,101621,01956670cf414b309675aa73368b94a9,transaction,282,19.92,NaN,NaN,M,52,20160825,95000.0,NaN,NaN,NaN,NaN,NaN
101622,101622,01956670cf414b309675aa73368b94a9,offer completed,282,NaN,2298d6c36e964ae4a3e7e9706d1fb8c2,3.0,M,52,20160825,95000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount
105021,105021,01956670cf414b309675aa73368b94a9,transaction,300,22.37,NaN,NaN,M,52,20160825,95000.0,NaN,NaN,NaN,NaN,NaN
106072,106072,01956670cf414b309675aa73368b94a9,transaction,306,29.28,NaN,NaN,M,52,20160825,95000.0,NaN,NaN,NaN,NaN,NaN
112758,112758,01956670cf414b309675aa73368b94a9,offer received,336,NaN,2906b810c7d4411798c6938adc9daaa5,NaN,M,52,20160825,95000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount
143842,143842,01956670cf414b309675aa73368b94a9,offer viewed,384,NaN,2906b810c7d4411798c6938adc9daaa5,NaN,M,52,20160825,95000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount
152556,152556,01956670cf414b309675aa73368b94a9,offer received,408,NaN,2906b810c7d4411798c6938adc9daaa5,NaN,M,52,20160825,95000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount
171645,171645,01956670cf414b309675aa73368b94a9,transaction,420,21.56,NaN,NaN,M,52,20160825,95000.0,NaN,NaN,NaN,NaN,NaN
171646,171646,01956670cf414b309675aa73368b94a9,offer completed,420,NaN,2906b810c7d4411798c6938adc9daaa5,2.0,M,52,20160825,95000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount
171647,171647,01956670cf414b309675aa73368b94a9,offer completed,420,NaN,2906b810c7d4411798c6938adc9daaa5,2.0,M,52,20160825,95000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount
203510,203510,01956670cf414b309675aa73368b94a9,offer received,504,NaN,ae264e3637204a6fb9bb56bc8210ddfd,NaN,M,52,20160825,95000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo
214904,214904,01956670cf414b309675aa73368b94a9,transaction,504,27.70,NaN,NaN,M,52,20160825,95000.0,NaN,NaN,NaN,NaN,NaN
214905,214905,01956670cf414b309675aa73368b94a9,offer completed,504,NaN,ae264e3637204a6fb9bb56bc8210ddfd,10.0,M,52,20160825,95000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo
269276,269276,01956670cf414b309675aa73368b94a9,offer viewed,594,NaN,ae264e3637204a6fb9bb56bc8210ddfd,NaN,M,52,20160825,95000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo
274920,274920,01956670cf414b309675aa73368b94a9,transaction,606,26.73,NaN,NaN,M,52,20160825,95000.0,NaN,NaN,NaN,NaN,NaN

- completed가 완료된 후 한참있다가 나오는 viewed 과연 정상적일까?

### 가설 2 동일 시간에 동일한 offer_id가 received되거나 viewed되면 이상하다?

In [17]:
rv_df = df_sorted[df_sorted['event'].isin(['offer received', 'offer viewed'])]

dup_rv_df = rv_df[rv_df.duplicated(subset=['person_id', 'time', 'event', 'offer_id'], keep=False)]

print(dup_rv_df['event'].value_counts())
print("-" * 80)

display(dup_rv_df[dup_rv_df['event'] == 'offer received'][
    ['person_id', 'time', 'event', 'offer_id']
])

display(dup_rv_df[dup_rv_df['event'] == 'offer viewed'][
    ['person_id', 'time', 'event', 'offer_id']
])

Series([], Name: count, dtype: int64)
--------------------------------------------------------------------------------

Empty DataFrame
Columns: [person_id, time, event, offer_id]
Index: []

Empty DataFrame
Columns: [person_id, time, event, offer_id]
Index: []

### 가설 3 received 되지않은 쿠폰에 대한 viewed나, completed가 있을까?

In [18]:
offer_events_df = df_sorted[df_sorted['event'].isin(['offer received', 'offer viewed', 'offer completed'])]

event_counts = offer_events_df.pivot_table(
    index=['person_id', 'offer_id'], 
    columns='event', 
    aggfunc='size', 
    fill_value=0
).reset_index()

event_counts.head(10)

event,person_id,offer_id,offer completed,offer received,offer viewed
0,0009655768c64bdeb2e877511632db8f,2906b810c7d4411798c6938adc9daaa5,1,1,0
1,0009655768c64bdeb2e877511632db8f,3f207df678b143eea3cee63160fa8bed,0,1,1
2,0009655768c64bdeb2e877511632db8f,5a8bc65990b245e5a138643cd4eb9837,0,1,1
3,0009655768c64bdeb2e877511632db8f,f19421c1d4aa40978ebb69ca19b0e20d,1,1,1
4,0009655768c64bdeb2e877511632db8f,fafdcd668e3743c1bb461111dcafc2a4,1,1,1
5,00116118485d4dfda04fdbaba9a87b5c,f19421c1d4aa40978ebb69ca19b0e20d,0,2,2
6,0011e0d4e6b944f998e987f904e8c1e5,0b1e1539f2cc45b7b9fa7c272da2e1d7,1,1,1
7,0011e0d4e6b944f998e987f904e8c1e5,2298d6c36e964ae4a3e7e9706d1fb8c2,1,1,1
8,0011e0d4e6b944f998e987f904e8c1e5,3f207df678b143eea3cee63160fa8bed,0,1,1
9,0011e0d4e6b944f998e987f904e8c1e5,5a8bc65990b245e5a138643cd4eb9837,0,1,1

In [19]:
error_cond1 = event_counts[event_counts['offer completed'] > event_counts['offer received']]
error_cond2 = event_counts[event_counts['offer viewed'] > event_counts['offer received']]
display(error_cond1)
display(error_cond2)

Empty DataFrame
Columns: [person_id, offer_id, offer completed, offer received, offer viewed]
Index: []

Empty DataFrame
Columns: [person_id, offer_id, offer completed, offer received, offer viewed]
Index: []

### 가설4) 역전 순서 찾기

In [20]:
# 1. 오퍼 관련 이벤트만 필터링 (df_sorted는 이미 person_id와 time 순으로 정렬되어 있음)
offer_events_df = df_sorted[df_sorted['event'].isin(['offer received', 'offer viewed', 'offer completed'])]

# 2. 고객(person_id)과 오퍼(offer_id)별로 그룹화하여 '가장 처음(first)' 발생한 이벤트 추출
first_events = offer_events_df.groupby(['person_id', 'offer_id']).first().reset_index()

# 3. 가장 처음 발생한 이벤트가 'offer received'가 아닌 경우 (즉, viewed나 completed가 먼저 온 경우)
time_anomalies = first_events[first_events['event'] != 'offer received']

In [21]:
time_anomalies

Empty DataFrame
Columns: [person_id, offer_id, index, event, time, amount, reward, gender, age, became_member_on, income, promotion_reward, promotion_channels, promotion_difficulty, promotion_duration, promotion_offer_type, prev_event, prev_time, next_event]
Index: []

In [22]:
# 데이터 정렬 (시간 흐름대로)
offer_events_df = df.sort_values(by=['person_id', 'offer_id', 'time']).copy()

# 각 행이 지날 때마다(시간이 흐를 때마다) 누적으로 몇 번 received/completed했는지 계산
# True/False(1/0)를 누적합(cumsum)하여 그 시점까지의 총 횟수를 구한다.
offer_events_df['cum_received'] = (offer_events_df['event'] == 'offer received').groupby(
    [offer_events_df['person_id'], offer_events_df['offer_id']]
).cumsum()

offer_events_df['cum_completed'] = (offer_events_df['event'] == 'offer completed').groupby(
    [offer_events_df['person_id'], offer_events_df['offer_id']]
).cumsum()

# 어느 순간이든 '누적 completed 수'가 '누적 received 수'를 초과한 적이 있는가?
sequence_errors = offer_events_df[offer_events_df['cum_completed'] > offer_events_df['cum_received']]

print(f"시간 순서 역전 오류 데이터 총 건수: {len(sequence_errors)}건\n")

시간 순서 역전 오류 데이터 총 건수: 0건

In [23]:
offer_events_df

,index,person_id,event,time,amount,offer_id,reward,gender,age,became_member_on,income,promotion_reward,promotion_channels,promotion_difficulty,promotion_duration,promotion_offer_type,cum_received,cum_completed
247879,247879,0009655768c64bdeb2e877511632db8f,offer received,576,NaN,2906b810c7d4411798c6938adc9daaa5,NaN,M,33,20170421,72000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,1.0,0.0
258884,258884,0009655768c64bdeb2e877511632db8f,offer completed,576,NaN,2906b810c7d4411798c6938adc9daaa5,2.0,M,33,20170421,72000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,1.0,1.0
113605,113605,0009655768c64bdeb2e877511632db8f,offer received,336,NaN,3f207df678b143eea3cee63160fa8bed,NaN,M,33,20170421,72000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,1.0,0.0
139992,139992,0009655768c64bdeb2e877511632db8f,offer viewed,372,NaN,3f207df678b143eea3cee63160fa8bed,NaN,M,33,20170421,72000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,1.0,0.0
55972,55972,0009655768c64bdeb2e877511632db8f,offer received,168,NaN,5a8bc65990b245e5a138643cd4eb9837,NaN,M,33,20170421,72000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200255,200255,ffff82501cea40309d5fdd7edcca4a07,transaction,498,13.17,NaN,NaN,F,45,20161125,62000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214716,214716,ffff82501cea40309d5fdd7edcca4a07,transaction,504,7.79,NaN,NaN,F,45,20161125,62000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258361,258361,ffff82501cea40309d5fdd7edcca4a07,transaction,576,14.23,NaN,NaN,F,45,20161125,62000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274809,274809,ffff82501cea40309d5fdd7edcca4a07,transaction,606,10.12,NaN,NaN,F,45,20161125,62000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289924,289924,ffff82501cea40309d5fdd7edcca4a07,transaction,648,18.91,NaN,NaN,F,45,20161125,62000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN